const express = require('express');
const cors = require('cors');

const app = express();
const PORT = 5000;

app.use(cors());

const songs = [
  // Core Collection
  { id: 1, title: "Mortals", artist: "Warriyo ft. Laura Brehm", cover: "/covers/1.jpg", file: "/songs/1.mp3", duration: "3:48", ytVideoId: "ltyf0PjonQg", genre: "Trap" },
  { id: 2, title: "Cielo", artist: "Huma-Huma", cover: "/covers/2.jpg", file: "/songs/2.mp3", duration: "2:02", ytVideoId: "ltyf0PjonQg", genre: "Electronic" },
  { id: 3, title: "Invincible", artist: "DEAF KEV", cover: "/covers/3.jpg", file: "/songs/3.mp3", duration: "4:33", ytVideoId: "5Dkfo0IjoBk", genre: "Gaming EDM" },
  { id: 4, title: "My Heart", artist: "Different Heaven & EH!DE", cover: "/covers/4.jpg", file: "/songs/4.mp3", duration: "4:27", ytVideoId: "5Dkfo0IjoBk", genre: "Dubstep" },
  { id: 5, title: "Heroes Tonight", artist: "Janji ft. Johnning", cover: "/covers/5.jpg", file: "/songs/5.mp3", duration: "3:28", ytVideoId: "jJbr4tzIGBI", genre: "Melodic House" },
  { id: 6, title: "Rabba", artist: "Salam-e-Ishq", cover: "/covers/6.jpg", file: "/songs/6.mp3", duration: "4:15", ytVideoId: "jJbr4tzIGBI", genre: "Bollywood" },
  { id: 7, title: "Sakhiyaan", artist: "Salam-e-Ishq", cover: "/covers/7.jpg", file: "/songs/7.mp3", duration: "3:50", ytVideoId: "jJbr4tzIGBI", genre: "Bollywood" },
  { id: 8, title: "Bhula Dena", artist: "Salam-e-Ishq", cover: "/covers/8.jpg", file: "/songs/8.mp3", duration: "4:40", ytVideoId: "7Pw5qk4wJAw", genre: "Romantic" },
  { id: 9, title: "Tumhari Kasam", artist: "Salam-e-Ishq", cover: "/covers/9.jpg", file: "/songs/9.mp3", duration: "3:30", ytVideoId: "7Pw5qk4wJAw", genre: "Melody" },
  { id: 10, title: "Na Jaana", artist: "Salam-e-Ishq", cover: "/covers/10.jpg", file: "/songs/10.mp3", duration: "4:10", ytVideoId: "7Pw5qk4wJAw", genre: "Lo-Fi" },

  // Special Pro YouTube Stream Stations (Direct In-App Audio) - using embeddable NCS release videos
  { id: 11, title: "NCS 24/7 Top Hits", artist: "NCS Official", cover: "https://img.youtube.com/vi/ltyf0PjonQg/hqdefault.jpg", file: "", ytVideoId: "ltyf0PjonQg", genre: "NCS Electronic", isSpecial: true, tag: "POPULAR" },
  { id: 12, title: "NCS Melodic & Chill Vibes", artist: "NCS Chill", cover: "https://img.youtube.com/vi/jJbr4tzIGBI/hqdefault.jpg", file: "", ytVideoId: "jJbr4tzIGBI", genre: "Chillstep", isSpecial: true, tag: "TRENDING" },
  { id: 13, title: "NCS Gaming Bass & Trap", artist: "NCS Bass", cover: "https://img.youtube.com/vi/5Dkfo0IjoBk/hqdefault.jpg", file: "", ytVideoId: "5Dkfo0IjoBk", genre: "Bass & Trap", isSpecial: true, tag: "GAMING" },
  { id: 14, title: "NCS Cyber Synth & Energy", artist: "NCS Synth", cover: "https://img.youtube.com/vi/Y8ETNh_IQjs/hqdefault.jpg", file: "", ytVideoId: "Y8ETNh_IQjs", genre: "Synthwave", isSpecial: true, tag: "CYBER" },
  { id: 15, title: "NCS Electro & Future House", artist: "NCS Club", cover: "https://img.youtube.com/vi/Z4B4mVV0NzM/hqdefault.jpg", file: "", ytVideoId: "Z4B4mVV0NzM", genre: "Future House", isSpecial: true, tag: "CLUB" },
  { id: 16, title: "NCS Lo-Fi & Ambient Beats", artist: "NCS Lounge", cover: "https://img.youtube.com/vi/7Pw5qk4wJAw/hqdefault.jpg", file: "", ytVideoId: "7Pw5qk4wJAw", genre: "Lo-Fi Chill", isSpecial: true, tag: "RELAX" },
  { id: 17, title: "NCS Phonk & Hard Bass", artist: "NCS Phonk", cover: "https://img.youtube.com/vi/rNXmANj72ps/hqdefault.jpg", file: "", ytVideoId: "rNXmANj72ps", genre: "Phonk & Bass", isSpecial: true, tag: "DRIFT" },
  { id: 128, title: "Track 128", artist: "YouTube Music", cover: "https://img.youtube.com/vi/maNMfH1dVR0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "maNMfH1dVR0", genre: "YouTube", isSpecial: false },
  { id: 129, title: "Track 129", artist: "YouTube Music", cover: "https://img.youtube.com/vi/slM5s55Jz0k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "slM5s55Jz0k", genre: "YouTube", isSpecial: false },
  { id: 130, title: "Track 130", artist: "YouTube Music", cover: "https://img.youtube.com/vi/VNs_cCtdbPc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "VNs_cCtdbPc", genre: "YouTube", isSpecial: false },
  { id: 131, title: "Track 131", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6piRLp7BV8o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6piRLp7BV8o", genre: "YouTube", isSpecial: false },
  { id: 132, title: "Track 132", artist: "YouTube Music", cover: "https://img.youtube.com/vi/nqUN530Rgtw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "nqUN530Rgtw", genre: "YouTube", isSpecial: false },
  { id: 133, title: "Track 133", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-YlmnPh-6rE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-YlmnPh-6rE", genre: "YouTube", isSpecial: false },
  { id: 134, title: "Track 134", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cl0a3i2wFcc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cl0a3i2wFcc", genre: "YouTube", isSpecial: false },
  { id: 135, title: "Track 135", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IltsOcCj1Ak/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IltsOcCj1Ak", genre: "YouTube", isSpecial: false },
  { id: 136, title: "Track 136", artist: "YouTube Music", cover: "https://img.youtube.com/vi/FfOwqhckUH8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "FfOwqhckUH8", genre: "YouTube", isSpecial: false },
  { id: 137, title: "Track 137", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ZUR5E18dvrA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ZUR5E18dvrA", genre: "YouTube", isSpecial: false },
  { id: 138, title: "Track 138", artist: "YouTube Music", cover: "https://img.youtube.com/vi/3ONzh3tf884/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "3ONzh3tf884", genre: "YouTube", isSpecial: false },
  { id: 139, title: "Track 139", artist: "YouTube Music", cover: "https://img.youtube.com/vi/fG70qm6usR8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "fG70qm6usR8", genre: "YouTube", isSpecial: false },
  { id: 140, title: "Track 140", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6RrEQJNZwPQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6RrEQJNZwPQ", genre: "YouTube", isSpecial: false },
  { id: 141, title: "Track 141", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RVh647FkPtA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RVh647FkPtA", genre: "YouTube", isSpecial: false },
  { id: 142, title: "Track 142", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6BYIKEH0RCQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6BYIKEH0RCQ", genre: "YouTube", isSpecial: false },
  { id: 143, title: "Track 143", artist: "YouTube Music", cover: "https://img.youtube.com/vi/TVbI55pDdaI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "TVbI55pDdaI", genre: "YouTube", isSpecial: false },
  { id: 144, title: "Track 144", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8nGFWWJLHio/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8nGFWWJLHio", genre: "YouTube", isSpecial: false },
  { id: 145, title: "Track 145", artist: "YouTube Music", cover: "https://img.youtube.com/vi/jADTdg-o8i0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "jADTdg-o8i0", genre: "YouTube", isSpecial: false },
  { id: 146, title: "Track 146", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vX2cDW8LUWk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vX2cDW8LUWk", genre: "YouTube", isSpecial: false },
  { id: 147, title: "Track 147", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0pWsCiBvLOk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0pWsCiBvLOk", genre: "YouTube", isSpecial: false },
  { id: 148, title: "Track 148", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cWMxCE2HTag/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cWMxCE2HTag", genre: "YouTube", isSpecial: false },
  { id: 149, title: "Track 149", artist: "YouTube Music", cover: "https://img.youtube.com/vi/YsCeMprm2O0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "YsCeMprm2O0", genre: "YouTube", isSpecial: false },
  { id: 150, title: "Track 150", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IAvw60x0Kn4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IAvw60x0Kn4", genre: "YouTube", isSpecial: false },
  { id: 151, title: "Track 151", artist: "YouTube Music", cover: "https://img.youtube.com/vi/pGuc4hPhiKw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "pGuc4hPhiKw", genre: "YouTube", isSpecial: false },
  { id: 152, title: "Track 152", artist: "YouTube Music", cover: "https://img.youtube.com/vi/BWczaSneA0Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "BWczaSneA0Q", genre: "YouTube", isSpecial: false },
  { id: 153, title: "Track 153", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2FhgKp_lfJQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2FhgKp_lfJQ", genre: "YouTube", isSpecial: false },
  { id: 154, title: "Track 154", artist: "YouTube Music", cover: "https://img.youtube.com/vi/5GCfYLguTIs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "5GCfYLguTIs", genre: "YouTube", isSpecial: false },
  { id: 155, title: "Track 155", artist: "YouTube Music", cover: "https://img.youtube.com/vi/3KXZduvOfDo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "3KXZduvOfDo", genre: "YouTube", isSpecial: false },
  { id: 156, title: "Track 156", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mGbkArS9Eyo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mGbkArS9Eyo", genre: "YouTube", isSpecial: false },
  { id: 157, title: "Track 157", artist: "YouTube Music", cover: "https://img.youtube.com/vi/CqDRlVWpzk8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "CqDRlVWpzk8", genre: "YouTube", isSpecial: false },
  
  { id: 159, title: "Track 159", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AsEd5OAys9E/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AsEd5OAys9E", genre: "YouTube", isSpecial: false },
  { id: 160, title: "Track 160", artist: "YouTube Music", cover: "https://img.youtube.com/vi/hjWf8A0YNSE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "hjWf8A0YNSE", genre: "YouTube", isSpecial: false },
  { id: 161, title: "Track 161", artist: "YouTube Music", cover: "https://img.youtube.com/vi/sxUh-Mq1t6Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "sxUh-Mq1t6Q", genre: "YouTube", isSpecial: false },
  { id: 162, title: "Track 162", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cfBLtdg5lYY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cfBLtdg5lYY", genre: "YouTube", isSpecial: false },
  
  { id: 164, title: "Track 164", artist: "YouTube Music", cover: "https://img.youtube.com/vi/4DfVxVeqk2o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "4DfVxVeqk2o", genre: "YouTube", isSpecial: false },
  
  { id: 166, title: "Track 166", artist: "YouTube Music", cover: "https://img.youtube.com/vi/WJP1HWB21EI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "WJP1HWB21EI", genre: "YouTube", isSpecial: false },
  { id: 167, title: "Track 167", artist: "YouTube Music", cover: "https://img.youtube.com/vi/E_SbwSe15y0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "E_SbwSe15y0", genre: "YouTube", isSpecial: false },
  { id: 168, title: "Track 168", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mpjNh-uGBY4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mpjNh-uGBY4", genre: "YouTube", isSpecial: false },
  { id: 169, title: "Track 169", artist: "YouTube Music", cover: "https://img.youtube.com/vi/PRXIG7ZWnG8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "PRXIG7ZWnG8", genre: "YouTube", isSpecial: false },
  { id: 170, title: "Track 170", artist: "YouTube Music", cover: "https://img.youtube.com/vi/oMesPehN_Do/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "oMesPehN_Do", genre: "YouTube", isSpecial: false },
  { id: 171, title: "Track 171", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ajGo94h0JxE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ajGo94h0JxE", genre: "YouTube", isSpecial: false },
  { id: 172, title: "Track 172", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8of5w7RgcTc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8of5w7RgcTc", genre: "YouTube", isSpecial: false },
  { id: 173, title: "Track 173", artist: "YouTube Music", cover: "https://img.youtube.com/vi/9T-Zbxg9X_4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "9T-Zbxg9X_4", genre: "YouTube", isSpecial: false },
  { id: 174, title: "Track 174", artist: "YouTube Music", cover: "https://img.youtube.com/vi/bP8ATWCvqzw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "bP8ATWCvqzw", genre: "YouTube", isSpecial: false },
  { id: 175, title: "Track 175", artist: "YouTube Music", cover: "https://img.youtube.com/vi/nJZcbidTutE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "nJZcbidTutE", genre: "YouTube", isSpecial: false },
  { id: 176, title: "Track 176", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0pKGaMHBCII/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0pKGaMHBCII", genre: "YouTube", isSpecial: false },
  { id: 177, title: "Track 177", artist: "YouTube Music", cover: "https://img.youtube.com/vi/25s_TeRqyHg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "25s_TeRqyHg", genre: "YouTube", isSpecial: false },
  { id: 178, title: "Track 178", artist: "YouTube Music", cover: "https://img.youtube.com/vi/KUpwupYj_tY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "KUpwupYj_tY", genre: "YouTube", isSpecial: false },
  { id: 179, title: "Track 179", artist: "YouTube Music", cover: "https://img.youtube.com/vi/jdxM0w253Gg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "jdxM0w253Gg", genre: "YouTube", isSpecial: false },
  { id: 180, title: "Track 180", artist: "YouTube Music", cover: "https://img.youtube.com/vi/b5WF7yZcc1w/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "b5WF7yZcc1w", genre: "YouTube", isSpecial: false },
  { id: 181, title: "Track 181", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mX3RdZGEGDM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mX3RdZGEGDM", genre: "YouTube", isSpecial: false },
  { id: 182, title: "Track 182", artist: "YouTube Music", cover: "https://img.youtube.com/vi/rmzeFqtk68s/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "rmzeFqtk68s", genre: "YouTube", isSpecial: false },
  { id: 183, title: "Track 183", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ZBMVHhSbF4U/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ZBMVHhSbF4U", genre: "YouTube", isSpecial: false },
  { id: 184, title: "Track 184", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DDYSI_GaNOU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DDYSI_GaNOU", genre: "YouTube", isSpecial: false },
  { id: 185, title: "Track 185", artist: "YouTube Music", cover: "https://img.youtube.com/vi/poT3qmuIarU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "poT3qmuIarU", genre: "YouTube", isSpecial: false },
  { id: 186, title: "Track 186", artist: "YouTube Music", cover: "https://img.youtube.com/vi/T94PHkuydcw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "T94PHkuydcw", genre: "YouTube", isSpecial: false },
  { id: 187, title: "Track 187", artist: "YouTube Music", cover: "https://img.youtube.com/vi/4YbAaRFk70o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "4YbAaRFk70o", genre: "YouTube", isSpecial: false },
  { id: 188, title: "Track 188", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xRb8hxwN5zc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xRb8hxwN5zc", genre: "YouTube", isSpecial: false },
  { id: 189, title: "Track 189", artist: "YouTube Music", cover: "https://img.youtube.com/vi/08CJzaeH8h4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "08CJzaeH8h4", genre: "YouTube", isSpecial: false },
  { id: 190, title: "Track 190", artist: "YouTube Music", cover: "https://img.youtube.com/vi/E45J_yOyUcA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "E45J_yOyUcA", genre: "YouTube", isSpecial: false },
  { id: 191, title: "Track 191", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DB3D-mtWR0c/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DB3D-mtWR0c", genre: "YouTube", isSpecial: false },
  { id: 192, title: "Track 192", artist: "YouTube Music", cover: "https://img.youtube.com/vi/orYf6VDtj_k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "orYf6VDtj_k", genre: "YouTube", isSpecial: false },
  { id: 193, title: "Track 193", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IZF-rOe9u-g/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IZF-rOe9u-g", genre: "YouTube", isSpecial: false },
  { id: 194, title: "Track 194", artist: "YouTube Music", cover: "https://img.youtube.com/vi/B4-HoKdW6j0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "B4-HoKdW6j0", genre: "YouTube", isSpecial: false },
  { id: 195, title: "Track 195", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RLzC55ai0eo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RLzC55ai0eo", genre: "YouTube", isSpecial: false },
  { id: 196, title: "Track 196", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JtnPpxe8K7c/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JtnPpxe8K7c", genre: "YouTube", isSpecial: false },
  { id: 197, title: "Track 197", artist: "YouTube Music", cover: "https://img.youtube.com/vi/1nWQs6IxTrY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "1nWQs6IxTrY", genre: "YouTube", isSpecial: false },
  { id: 198, title: "Track 198", artist: "YouTube Music", cover: "https://img.youtube.com/vi/GLGuLXKT9Ng/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "GLGuLXKT9Ng", genre: "YouTube", isSpecial: false },
  { id: 199, title: "Track 199", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8_KBlCKK-0k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8_KBlCKK-0k", genre: "YouTube", isSpecial: false },
  { id: 200, title: "Track 200", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LlI1IkgP6BQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LlI1IkgP6BQ", genre: "YouTube", isSpecial: false },
  { id: 201, title: "Track 201", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8A1XPxaeoZA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8A1XPxaeoZA", genre: "YouTube", isSpecial: false },
  { id: 202, title: "Track 202", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-rmGyJnTKXw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-rmGyJnTKXw", genre: "YouTube", isSpecial: false },
  { id: 203, title: "Track 203", artist: "YouTube Music", cover: "https://img.youtube.com/vi/CQNJE7ZXHg0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "CQNJE7ZXHg0", genre: "YouTube", isSpecial: false },
  { id: 204, title: "Track 204", artist: "YouTube Music", cover: "https://img.youtube.com/vi/YrJ6OZ7VVWc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "YrJ6OZ7VVWc", genre: "YouTube", isSpecial: false },
  { id: 205, title: "Track 205", artist: "YouTube Music", cover: "https://img.youtube.com/vi/HZHVbmnkuzU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "HZHVbmnkuzU", genre: "YouTube", isSpecial: false },
  { id: 206, title: "Track 206", artist: "YouTube Music", cover: "https://img.youtube.com/vi/3u__IvHX_rI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "3u__IvHX_rI", genre: "YouTube", isSpecial: false },
  { id: 207, title: "Track 207", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LPeZOE8ZIHI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LPeZOE8ZIHI", genre: "YouTube", isSpecial: false },
  { id: 208, title: "Track 208", artist: "YouTube Music", cover: "https://img.youtube.com/vi/piUHBTXsoiY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "piUHBTXsoiY", genre: "YouTube", isSpecial: false },
  { id: 209, title: "Track 209", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vJiDTHrq6DI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vJiDTHrq6DI", genre: "YouTube", isSpecial: false },
  { id: 210, title: "Track 210", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ESpTwlItxpQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ESpTwlItxpQ", genre: "YouTube", isSpecial: false },
  { id: 211, title: "Track 211", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vJQCAtzSfuo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vJQCAtzSfuo", genre: "YouTube", isSpecial: false },
  { id: 212, title: "Track 212", artist: "YouTube Music", cover: "https://img.youtube.com/vi/lBvbNxiVmZA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "lBvbNxiVmZA", genre: "YouTube", isSpecial: false },
  { id: 213, title: "Track 213", artist: "YouTube Music", cover: "https://img.youtube.com/vi/amWKXh9_EQE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "amWKXh9_EQE", genre: "YouTube", isSpecial: false },
  { id: 214, title: "Track 214", artist: "YouTube Music", cover: "https://img.youtube.com/vi/se9DDAwwGQY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "se9DDAwwGQY", genre: "YouTube", isSpecial: false },
  { id: 215, title: "Track 215", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JQuVBmyhW08/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JQuVBmyhW08", genre: "YouTube", isSpecial: false },
  { id: 216, title: "Track 216", artist: "YouTube Music", cover: "https://img.youtube.com/vi/akjdj6iHttY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "akjdj6iHttY", genre: "YouTube", isSpecial: false },
  { id: 217, title: "Track 217", artist: "YouTube Music", cover: "https://img.youtube.com/vi/psXl8w6gQuA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "psXl8w6gQuA", genre: "YouTube", isSpecial: false },
  { id: 218, title: "Track 218", artist: "YouTube Music", cover: "https://img.youtube.com/vi/MOh4qB12vJY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "MOh4qB12vJY", genre: "YouTube", isSpecial: false },
  { id: 219, title: "Track 219", artist: "YouTube Music", cover: "https://img.youtube.com/vi/tsVe7wHl_GQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "tsVe7wHl_GQ", genre: "YouTube", isSpecial: false },
  { id: 220, title: "Track 220", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yDv0WSgXJVg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yDv0WSgXJVg", genre: "YouTube", isSpecial: false },
  { id: 221, title: "Track 221", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8z5GZVURqAg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8z5GZVURqAg", genre: "YouTube", isSpecial: false },
  { id: 222, title: "Track 222", artist: "YouTube Music", cover: "https://img.youtube.com/vi/M7vXOK_ZKY0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "M7vXOK_ZKY0", genre: "YouTube", isSpecial: false },
  { id: 223, title: "Track 223", artist: "YouTube Music", cover: "https://img.youtube.com/vi/dpwTb9ecLXE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "dpwTb9ecLXE", genre: "YouTube", isSpecial: false },
  { id: 224, title: "Track 224", artist: "YouTube Music", cover: "https://img.youtube.com/vi/c2gSzYLJ8sY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "c2gSzYLJ8sY", genre: "YouTube", isSpecial: false },
  { id: 225, title: "Track 225", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yy-ELf7JpMw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yy-ELf7JpMw", genre: "YouTube", isSpecial: false },
  { id: 226, title: "Track 226", artist: "YouTube Music", cover: "https://img.youtube.com/vi/udgrClXV26Y/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "udgrClXV26Y", genre: "YouTube", isSpecial: false },
  { id: 227, title: "Track 227", artist: "YouTube Music", cover: "https://img.youtube.com/vi/_mR6bY-ndso/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "_mR6bY-ndso", genre: "YouTube", isSpecial: false },
  { id: 228, title: "Track 228", artist: "YouTube Music", cover: "https://img.youtube.com/vi/KTki8bU8wg8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "KTki8bU8wg8", genre: "YouTube", isSpecial: false },
  { id: 229, title: "Track 229", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ZJ5HxNWYDtM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ZJ5HxNWYDtM", genre: "YouTube", isSpecial: false },
  { id: 230, title: "Track 230", artist: "YouTube Music", cover: "https://img.youtube.com/vi/pmId7mXRKS4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "pmId7mXRKS4", genre: "YouTube", isSpecial: false },
  { id: 231, title: "Track 231", artist: "YouTube Music", cover: "https://img.youtube.com/vi/B7SkAq_94J8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "B7SkAq_94J8", genre: "YouTube", isSpecial: false },
  { id: 232, title: "Track 232", artist: "YouTube Music", cover: "https://img.youtube.com/vi/7Qq4m-bw71g/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "7Qq4m-bw71g", genre: "YouTube", isSpecial: false },
  { id: 233, title: "Track 233", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SivCc33LxyA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SivCc33LxyA", genre: "YouTube", isSpecial: false },
  { id: 234, title: "Track 234", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xgbgjQWwwIE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xgbgjQWwwIE", genre: "YouTube", isSpecial: false },
  { id: 235, title: "Track 235", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AIWBZbHyNpI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AIWBZbHyNpI", genre: "YouTube", isSpecial: false },
  { id: 236, title: "Track 236", artist: "YouTube Music", cover: "https://img.youtube.com/vi/t_sCtNmZPwQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "t_sCtNmZPwQ", genre: "YouTube", isSpecial: false },
  { id: 237, title: "Track 237", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xdZiUuwZeOI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xdZiUuwZeOI", genre: "YouTube", isSpecial: false },
  { id: 238, title: "Track 238", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LV_wiOhO40Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LV_wiOhO40Q", genre: "YouTube", isSpecial: false },
  { id: 239, title: "Track 239", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SQ4jZ-EAL88/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SQ4jZ-EAL88", genre: "YouTube", isSpecial: false },
  { id: 240, title: "Track 240", artist: "YouTube Music", cover: "https://img.youtube.com/vi/D9yb5ffKkVo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "D9yb5ffKkVo", genre: "YouTube", isSpecial: false },
  { id: 241, title: "Track 241", artist: "YouTube Music", cover: "https://img.youtube.com/vi/prKlWuv3-PQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "prKlWuv3-PQ", genre: "YouTube", isSpecial: false },
  { id: 242, title: "Track 242", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RG-a2kVQcGg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RG-a2kVQcGg", genre: "YouTube", isSpecial: false },
  { id: 243, title: "Track 243", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SMlGGRAB3Hc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SMlGGRAB3Hc", genre: "YouTube", isSpecial: false },
  { id: 244, title: "Track 244", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ilNt2bikxDI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ilNt2bikxDI", genre: "YouTube", isSpecial: false },
  { id: 245, title: "Track 245", artist: "YouTube Music", cover: "https://img.youtube.com/vi/jfOi7dscWc8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "jfOi7dscWc8", genre: "YouTube", isSpecial: false },
  { id: 246, title: "Track 246", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SxTYjptEzZs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SxTYjptEzZs", genre: "YouTube", isSpecial: false },
  { id: 247, title: "Track 247", artist: "YouTube Music", cover: "https://img.youtube.com/vi/U0EI7XFkkV4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "U0EI7XFkkV4", genre: "YouTube", isSpecial: false },
  { id: 248, title: "Track 248", artist: "YouTube Music", cover: "https://img.youtube.com/vi/GnGhZtIcIh0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "GnGhZtIcIh0", genre: "YouTube", isSpecial: false },
  { id: 249, title: "Track 249", artist: "YouTube Music", cover: "https://img.youtube.com/vi/BWczaSneA0Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "BWczaSneA0Q", genre: "YouTube", isSpecial: false },
  { id: 250, title: "Track 250", artist: "YouTube Music", cover: "https://img.youtube.com/vi/usvVGXFIpTM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "usvVGXFIpTM", genre: "YouTube", isSpecial: false },
  { id: 251, title: "Track 251", artist: "YouTube Music", cover: "https://img.youtube.com/vi/NLKwRW2y-sg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "NLKwRW2y-sg", genre: "YouTube", isSpecial: false },
  { id: 252, title: "Track 252", artist: "YouTube Music", cover: "https://img.youtube.com/vi/a18py61_F_w/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "a18py61_F_w", genre: "YouTube", isSpecial: false },
  { id: 253, title: "Track 253", artist: "YouTube Music", cover: "https://img.youtube.com/vi/TuUVVKVdZm4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "TuUVVKVdZm4", genre: "YouTube", isSpecial: false },
  { id: 254, title: "Track 254", artist: "YouTube Music", cover: "https://img.youtube.com/vi/WPwTPhFMm3k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "WPwTPhFMm3k", genre: "YouTube", isSpecial: false },
  { id: 255, title: "Track 255", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Cb6wuzOurPc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Cb6wuzOurPc", genre: "YouTube", isSpecial: false },
  { id: 256, title: "Track 256", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2mWaqsC3U7k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2mWaqsC3U7k", genre: "YouTube", isSpecial: false },
  { id: 257, title: "Track 257", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6vKucgAeF_Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6vKucgAeF_Q", genre: "YouTube", isSpecial: false },
  { id: 258, title: "Track 258", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xHLnZMjJ8bY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xHLnZMjJ8bY", genre: "YouTube", isSpecial: false },
  { id: 259, title: "Track 259", artist: "YouTube Music", cover: "https://img.youtube.com/vi/b_sCZbYyuO4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "b_sCZbYyuO4", genre: "YouTube", isSpecial: false },
  { id: 260, title: "Track 260", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yIyVhIspa2I/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yIyVhIspa2I", genre: "YouTube", isSpecial: false },
  { id: 261, title: "Track 261", artist: "YouTube Music", cover: "https://img.youtube.com/vi/dTu5dTEzVM4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "dTu5dTEzVM4", genre: "YouTube", isSpecial: false },
  { id: 262, title: "Track 262", artist: "YouTube Music", cover: "https://img.youtube.com/vi/u7hfwX81bY4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "u7hfwX81bY4", genre: "YouTube", isSpecial: false },
  { id: 263, title: "Track 263", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DKOLynNhWxo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DKOLynNhWxo", genre: "YouTube", isSpecial: false },
  { id: 264, title: "Track 264", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ru_5PA8cwkE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ru_5PA8cwkE", genre: "YouTube", isSpecial: false },
  { id: 265, title: "Track 265", artist: "YouTube Music", cover: "https://img.youtube.com/vi/o1RducJbUdc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "o1RducJbUdc", genre: "YouTube", isSpecial: false },
  { id: 266, title: "Track 266", artist: "YouTube Music", cover: "https://img.youtube.com/vi/HqUeSjsYLNU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "HqUeSjsYLNU", genre: "YouTube", isSpecial: false },
  { id: 267, title: "Track 267", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JbDktrsnH40/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JbDktrsnH40", genre: "YouTube", isSpecial: false },
  { id: 268, title: "Track 268", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kPtn26x8TZM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kPtn26x8TZM", genre: "YouTube", isSpecial: false },
  { id: 269, title: "Track 269", artist: "YouTube Music", cover: "https://img.youtube.com/vi/QYO6AlxiRE4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "QYO6AlxiRE4", genre: "YouTube", isSpecial: false },
  { id: 270, title: "Track 270", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RbcG85TK-wM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RbcG85TK-wM", genre: "YouTube", isSpecial: false },
  { id: 271, title: "Track 271", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kyDXsLhlwv0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kyDXsLhlwv0", genre: "YouTube", isSpecial: false },
  { id: 272, title: "Track 272", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0gLqP1IZUPg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0gLqP1IZUPg", genre: "YouTube", isSpecial: false },
  { id: 273, title: "Track 273", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Rwy8nryH3gY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Rwy8nryH3gY", genre: "YouTube", isSpecial: false },
  { id: 274, title: "Track 274", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cWMxCE2HTag/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cWMxCE2HTag", genre: "YouTube", isSpecial: false },
  { id: 275, title: "Track 275", artist: "YouTube Music", cover: "https://img.youtube.com/vi/k85UB5b6pJU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "k85UB5b6pJU", genre: "YouTube", isSpecial: false },
  { id: 276, title: "Track 276", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vsWxs1tuwDk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vsWxs1tuwDk", genre: "YouTube", isSpecial: false },
  { id: 277, title: "Track 277", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LK7-_dgAVQE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LK7-_dgAVQE", genre: "YouTube", isSpecial: false },
  { id: 278, title: "Track 278", artist: "YouTube Music", cover: "https://img.youtube.com/vi/XTp5jaRU3Ws/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "XTp5jaRU3Ws", genre: "YouTube", isSpecial: false },
  { id: 279, title: "Track 279", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Fbv6-50S1lc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Fbv6-50S1lc", genre: "YouTube", isSpecial: false },
  { id: 280, title: "Track 280", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0dXiVYq8HBc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0dXiVYq8HBc", genre: "YouTube", isSpecial: false },
  { id: 281, title: "Track 281", artist: "YouTube Music", cover: "https://img.youtube.com/vi/FRdcZKWjJPc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "FRdcZKWjJPc", genre: "YouTube", isSpecial: false },
  { id: 282, title: "Track 282", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8PTOkwze0Vw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8PTOkwze0Vw", genre: "YouTube", isSpecial: false },
  { id: 283, title: "Track 283", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IgnbfHEfvpo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IgnbfHEfvpo", genre: "YouTube", isSpecial: false },
  { id: 284, title: "Track 284", artist: "YouTube Music", cover: "https://img.youtube.com/vi/wlC_eFbxwDo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "wlC_eFbxwDo", genre: "YouTube", isSpecial: false },
  { id: 285, title: "Track 285", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Pi8Oh3jq3u0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Pi8Oh3jq3u0", genre: "YouTube", isSpecial: false },
  { id: 286, title: "Track 286", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LOZNKZfiFUw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LOZNKZfiFUw", genre: "YouTube", isSpecial: false },
  { id: 287, title: "Track 287", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IEnCPUOl2UM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IEnCPUOl2UM", genre: "YouTube", isSpecial: false },
  { id: 288, title: "Track 288", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2ySr4lR0XFg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2ySr4lR0XFg", genre: "YouTube", isSpecial: false },
  { id: 289, title: "Track 289", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Kn9FJsNOaUU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Kn9FJsNOaUU", genre: "YouTube", isSpecial: false },
  { id: 290, title: "Track 290", artist: "YouTube Music", cover: "https://img.youtube.com/vi/OsTGp5n6w5E/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "OsTGp5n6w5E", genre: "YouTube", isSpecial: false },
  { id: 291, title: "Track 291", artist: "YouTube Music", cover: "https://img.youtube.com/vi/4dsFQFCvVGU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "4dsFQFCvVGU", genre: "YouTube", isSpecial: false },
  { id: 292, title: "Track 292", artist: "YouTube Music", cover: "https://img.youtube.com/vi/bL6dJjxm0x0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "bL6dJjxm0x0", genre: "YouTube", isSpecial: false },
  { id: 293, title: "Track 293", artist: "YouTube Music", cover: "https://img.youtube.com/vi/nwXAkF8OFCc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "nwXAkF8OFCc", genre: "YouTube", isSpecial: false },
  { id: 294, title: "Track 294", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kw6SFbbinnY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kw6SFbbinnY", genre: "YouTube", isSpecial: false },
  { id: 295, title: "Track 295", artist: "YouTube Music", cover: "https://img.youtube.com/vi/v2IGNN7CA4M/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "v2IGNN7CA4M", genre: "YouTube", isSpecial: false },
  { id: 296, title: "Track 296", artist: "YouTube Music", cover: "https://img.youtube.com/vi/pUwpLoLlzNQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "pUwpLoLlzNQ", genre: "YouTube", isSpecial: false },
  { id: 297, title: "Track 297", artist: "YouTube Music", cover: "https://img.youtube.com/vi/BAJ08Fe3VhM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "BAJ08Fe3VhM", genre: "YouTube", isSpecial: false },
  { id: 298, title: "Track 298", artist: "YouTube Music", cover: "https://img.youtube.com/vi/epAFDEJImrU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "epAFDEJImrU", genre: "YouTube", isSpecial: false },
  { id: 299, title: "Track 299", artist: "YouTube Music", cover: "https://img.youtube.com/vi/lZL2K3ewRYM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "lZL2K3ewRYM", genre: "YouTube", isSpecial: false },
  { id: 300, title: "Track 300", artist: "YouTube Music", cover: "https://img.youtube.com/vi/N_zXtXla2-c/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "N_zXtXla2-c", genre: "YouTube", isSpecial: false },
  { id: 301, title: "Track 301", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ftIPUowtX2Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ftIPUowtX2Q", genre: "YouTube", isSpecial: false },
  { id: 302, title: "Track 302", artist: "YouTube Music", cover: "https://img.youtube.com/vi/u0RXWL2JGNE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "u0RXWL2JGNE", genre: "YouTube", isSpecial: false },
  { id: 303, title: "Track 303", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JXT2YfC298k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JXT2YfC298k", genre: "YouTube", isSpecial: false },
  
  { id: 305, title: "Track 305", artist: "YouTube Music", cover: "https://img.youtube.com/vi/UyK2GMvyNok/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "UyK2GMvyNok", genre: "YouTube", isSpecial: false },
  { id: 306, title: "Track 306", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8eYGGp_o6as/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8eYGGp_o6as", genre: "YouTube", isSpecial: false },
  { id: 307, title: "Track 307", artist: "YouTube Music", cover: "https://img.youtube.com/vi/XckXMFgdAEQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "XckXMFgdAEQ", genre: "YouTube", isSpecial: false },
  { id: 308, title: "Track 308", artist: "YouTube Music", cover: "https://img.youtube.com/vi/tW7P0RXsCSk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "tW7P0RXsCSk", genre: "YouTube", isSpecial: false },
  { id: 309, title: "Track 309", artist: "YouTube Music", cover: "https://img.youtube.com/vi/trDHmX2-eOs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "trDHmX2-eOs", genre: "YouTube", isSpecial: false },
  { id: 310, title: "Track 310", artist: "YouTube Music", cover: "https://img.youtube.com/vi/brBokVUqhyg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "brBokVUqhyg", genre: "YouTube", isSpecial: false },
  { id: 311, title: "Track 311", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JNw2mhipMM8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JNw2mhipMM8", genre: "YouTube", isSpecial: false },
  { id: 312, title: "Track 312", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vdiqoJ04ZRk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vdiqoJ04ZRk", genre: "YouTube", isSpecial: false },
  { id: 313, title: "Track 313", artist: "YouTube Music", cover: "https://img.youtube.com/vi/VYdWSp8pIjg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "VYdWSp8pIjg", genre: "YouTube", isSpecial: false },
  { id: 314, title: "Track 314", artist: "YouTube Music", cover: "https://img.youtube.com/vi/H4K_ET2WHf8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "H4K_ET2WHf8", genre: "YouTube", isSpecial: false },
  { id: 315, title: "Track 315", artist: "YouTube Music", cover: "https://img.youtube.com/vi/XzcdYefPCmY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "XzcdYefPCmY", genre: "YouTube", isSpecial: false },
  { id: 316, title: "Track 316", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-CChWdx_pF4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-CChWdx_pF4", genre: "YouTube", isSpecial: false },
  { id: 317, title: "Track 317", artist: "YouTube Music", cover: "https://img.youtube.com/vi/4HRC6c5-2lQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "4HRC6c5-2lQ", genre: "YouTube", isSpecial: false },
  { id: 318, title: "Track 318", artist: "YouTube Music", cover: "https://img.youtube.com/vi/iasxMdSu7Jo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "iasxMdSu7Jo", genre: "YouTube", isSpecial: false },
  { id: 319, title: "Track 319", artist: "YouTube Music", cover: "https://img.youtube.com/vi/9dkPy-II5-4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "9dkPy-II5-4", genre: "YouTube", isSpecial: false },
  { id: 320, title: "Track 320", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kMfTm0NfNgI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kMfTm0NfNgI", genre: "YouTube", isSpecial: false },
  { id: 321, title: "Track 321", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Iw8NxpQMVzs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Iw8NxpQMVzs", genre: "YouTube", isSpecial: false },
  { id: 322, title: "Track 322", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6bmDbIk8zUc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6bmDbIk8zUc", genre: "YouTube", isSpecial: false },
  { id: 323, title: "Track 323", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Onb6_bRJ0Bw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Onb6_bRJ0Bw", genre: "YouTube", isSpecial: false },
  { id: 324, title: "Track 324", artist: "YouTube Music", cover: "https://img.youtube.com/vi/D8l3fLJ1Klw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "D8l3fLJ1Klw", genre: "YouTube", isSpecial: false },
  { id: 325, title: "Track 325", artist: "YouTube Music", cover: "https://img.youtube.com/vi/M5OCLifZK1w/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "M5OCLifZK1w", genre: "YouTube", isSpecial: false },
  { id: 326, title: "Track 326", artist: "YouTube Music", cover: "https://img.youtube.com/vi/gqZN6ILVx38/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "gqZN6ILVx38", genre: "YouTube", isSpecial: false },
  { id: 327, title: "Track 327", artist: "YouTube Music", cover: "https://img.youtube.com/vi/EMC3IXmrcAc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "EMC3IXmrcAc", genre: "YouTube", isSpecial: false },
  { id: 328, title: "Track 328", artist: "YouTube Music", cover: "https://img.youtube.com/vi/F1hkaRCJTCc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "F1hkaRCJTCc", genre: "YouTube", isSpecial: false },
  { id: 329, title: "Track 329", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-FLi3SqKBOI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-FLi3SqKBOI", genre: "YouTube", isSpecial: false },
  { id: 330, title: "Track 330", artist: "YouTube Music", cover: "https://img.youtube.com/vi/v2-9rIL_f4w/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "v2-9rIL_f4w", genre: "YouTube", isSpecial: false },
  { id: 331, title: "Track 331", artist: "YouTube Music", cover: "https://img.youtube.com/vi/y9mJNwPly44/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "y9mJNwPly44", genre: "YouTube", isSpecial: false },
  { id: 332, title: "Track 332", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JOMGQO2WL3o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JOMGQO2WL3o", genre: "YouTube", isSpecial: false },
  { id: 333, title: "Track 333", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-aMb8aRvpCo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-aMb8aRvpCo", genre: "YouTube", isSpecial: false },
  { id: 334, title: "Track 334", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Hc7BjYmn9z0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Hc7BjYmn9z0", genre: "YouTube", isSpecial: false },
  { id: 335, title: "Track 335", artist: "YouTube Music", cover: "https://img.youtube.com/vi/HjdsR87AgRM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "HjdsR87AgRM", genre: "YouTube", isSpecial: false },
  { id: 336, title: "Track 336", artist: "YouTube Music", cover: "https://img.youtube.com/vi/X18PQ74DH4g/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "X18PQ74DH4g", genre: "YouTube", isSpecial: false },
  { id: 337, title: "Track 337", artist: "YouTube Music", cover: "https://img.youtube.com/vi/BewnzhHlQuk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "BewnzhHlQuk", genre: "YouTube", isSpecial: false },
  { id: 338, title: "Track 338", artist: "YouTube Music", cover: "https://img.youtube.com/vi/_mNi5MQ3k48/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "_mNi5MQ3k48", genre: "YouTube", isSpecial: false },
  { id: 339, title: "Track 339", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2CXSw1oPj3I/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2CXSw1oPj3I", genre: "YouTube", isSpecial: false },
  { id: 340, title: "Track 340", artist: "YouTube Music", cover: "https://img.youtube.com/vi/MXs802oGzio/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "MXs802oGzio", genre: "YouTube", isSpecial: false },
  { id: 341, title: "Track 341", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kH_wJOH1CS0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kH_wJOH1CS0", genre: "YouTube", isSpecial: false },
  { id: 342, title: "Track 342", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ROJ_mvbYzJE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ROJ_mvbYzJE", genre: "YouTube", isSpecial: false },
  { id: 343, title: "Track 343", artist: "YouTube Music", cover: "https://img.youtube.com/vi/uiBIkQlJ3pA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "uiBIkQlJ3pA", genre: "YouTube", isSpecial: false },
  { id: 344, title: "Track 344", artist: "YouTube Music", cover: "https://img.youtube.com/vi/gkds6yVdDLI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "gkds6yVdDLI", genre: "YouTube", isSpecial: false },
  { id: 345, title: "Track 345", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DEISa38m8rA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DEISa38m8rA", genre: "YouTube", isSpecial: false },
  { id: 346, title: "Track 346", artist: "YouTube Music", cover: "https://img.youtube.com/vi/o-7b6ctrQX0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "o-7b6ctrQX0", genre: "YouTube", isSpecial: false },
  { id: 347, title: "Track 347", artist: "YouTube Music", cover: "https://img.youtube.com/vi/QW_5uoG2q90/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "QW_5uoG2q90", genre: "YouTube", isSpecial: false },
  { id: 348, title: "Track 348", artist: "YouTube Music", cover: "https://img.youtube.com/vi/g3SCgXV1OUw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "g3SCgXV1OUw", genre: "YouTube", isSpecial: false },
  { id: 349, title: "Track 349", artist: "YouTube Music", cover: "https://img.youtube.com/vi/9z1Ub96VZWs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "9z1Ub96VZWs", genre: "YouTube", isSpecial: false },
  { id: 350, title: "Track 350", artist: "YouTube Music", cover: "https://img.youtube.com/vi/C5Eb8nNcA_s/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "C5Eb8nNcA_s", genre: "YouTube", isSpecial: false },
  { id: 351, title: "Track 351", artist: "YouTube Music", cover: "https://img.youtube.com/vi/4olD6O83204/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "4olD6O83204", genre: "YouTube", isSpecial: false },
  { id: 352, title: "Track 352", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mPhboJR0Llc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mPhboJR0Llc", genre: "YouTube", isSpecial: false },
  { id: 353, title: "Track 353", artist: "YouTube Music", cover: "https://img.youtube.com/vi/26iXuJSBG-w/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "26iXuJSBG-w", genre: "YouTube", isSpecial: false },
  { id: 354, title: "Track 354", artist: "YouTube Music", cover: "https://img.youtube.com/vi/WCTro3qabjE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "WCTro3qabjE", genre: "YouTube", isSpecial: false },
  { id: 355, title: "Track 355", artist: "YouTube Music", cover: "https://img.youtube.com/vi/HqjPEwhiWcE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "HqjPEwhiWcE", genre: "YouTube", isSpecial: false },
  { id: 356, title: "Track 356", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AB-I3vsUk6g/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AB-I3vsUk6g", genre: "YouTube", isSpecial: false },
  { id: 357, title: "Track 357", artist: "YouTube Music", cover: "https://img.youtube.com/vi/9mZugcDsM4Y/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "9mZugcDsM4Y", genre: "YouTube", isSpecial: false },
  { id: 358, title: "Track 358", artist: "YouTube Music", cover: "https://img.youtube.com/vi/rnyrDk4G68g/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "rnyrDk4G68g", genre: "YouTube", isSpecial: false },
  { id: 359, title: "Track 359", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kTXilT_KbUM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kTXilT_KbUM", genre: "YouTube", isSpecial: false },
  { id: 360, title: "Track 360", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JfxlsiFztLs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JfxlsiFztLs", genre: "YouTube", isSpecial: false },
  { id: 361, title: "Track 361", artist: "YouTube Music", cover: "https://img.youtube.com/vi/c7POv4qiZLM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "c7POv4qiZLM", genre: "YouTube", isSpecial: false },
  { id: 362, title: "Track 362", artist: "YouTube Music", cover: "https://img.youtube.com/vi/hejXc_FSYb8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "hejXc_FSYb8", genre: "YouTube", isSpecial: false },
  { id: 363, title: "Track 363", artist: "YouTube Music", cover: "https://img.youtube.com/vi/7LRMVzjylpA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "7LRMVzjylpA", genre: "YouTube", isSpecial: false },
  { id: 364, title: "Track 364", artist: "YouTube Music", cover: "https://img.youtube.com/vi/k6a0ksWo1X4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "k6a0ksWo1X4", genre: "YouTube", isSpecial: false },
  { id: 365, title: "Track 365", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2ibPLYwVM38/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2ibPLYwVM38", genre: "YouTube", isSpecial: false },
  { id: 366, title: "Track 366", artist: "YouTube Music", cover: "https://img.youtube.com/vi/hk0u0PAlDWQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "hk0u0PAlDWQ", genre: "YouTube", isSpecial: false },
  { id: 367, title: "Track 367", artist: "YouTube Music", cover: "https://img.youtube.com/vi/XuIz4e47NLQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "XuIz4e47NLQ", genre: "YouTube", isSpecial: false },
  { id: 368, title: "Track 368", artist: "YouTube Music", cover: "https://img.youtube.com/vi/7KKVb0_IdD4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "7KKVb0_IdD4", genre: "YouTube", isSpecial: false },
  { id: 369, title: "Track 369", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IImcBEHuDRI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IImcBEHuDRI", genre: "YouTube", isSpecial: false },
  { id: 370, title: "Track 370", artist: "YouTube Music", cover: "https://img.youtube.com/vi/f6EmxM8_XPk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "f6EmxM8_XPk", genre: "YouTube", isSpecial: false },
  { id: 371, title: "Track 371", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2tcGMjvoIsI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2tcGMjvoIsI", genre: "YouTube", isSpecial: false },
  { id: 372, title: "Track 372", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ERWoyZ-rmHY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ERWoyZ-rmHY", genre: "YouTube", isSpecial: false },
  { id: 373, title: "Track 373", artist: "YouTube Music", cover: "https://img.youtube.com/vi/d8IT-16kA8M/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "d8IT-16kA8M", genre: "YouTube", isSpecial: false },
  { id: 374, title: "Track 374", artist: "YouTube Music", cover: "https://img.youtube.com/vi/zfABYXP_NSA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "zfABYXP_NSA", genre: "YouTube", isSpecial: false },
  { id: 375, title: "Track 375", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xtoUfyFoVck/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xtoUfyFoVck", genre: "YouTube", isSpecial: false },
  { id: 376, title: "Track 376", artist: "YouTube Music", cover: "https://img.youtube.com/vi/nZhLM-FeV9A/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "nZhLM-FeV9A", genre: "YouTube", isSpecial: false },
  { id: 377, title: "Track 377", artist: "YouTube Music", cover: "https://img.youtube.com/vi/BaXVWssb17Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "BaXVWssb17Q", genre: "YouTube", isSpecial: false },
  { id: 378, title: "Track 378", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vr8RaNuWjWc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vr8RaNuWjWc", genre: "YouTube", isSpecial: false },
  { id: 379, title: "Track 379", artist: "YouTube Music", cover: "https://img.youtube.com/vi/_zxKyIO7o8U/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "_zxKyIO7o8U", genre: "YouTube", isSpecial: false },
  { id: 380, title: "Track 380", artist: "YouTube Music", cover: "https://img.youtube.com/vi/sTRps18IAlw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "sTRps18IAlw", genre: "YouTube", isSpecial: false },
  { id: 381, title: "Track 381", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Y35uCA-XVRM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Y35uCA-XVRM", genre: "YouTube", isSpecial: false },
  { id: 382, title: "Track 382", artist: "YouTube Music", cover: "https://img.youtube.com/vi/5jOqWOZTusg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "5jOqWOZTusg", genre: "YouTube", isSpecial: false },
  { id: 383, title: "Track 383", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-JD8B4Gf4Sc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-JD8B4Gf4Sc", genre: "YouTube", isSpecial: false },
  { id: 384, title: "Track 384", artist: "YouTube Music", cover: "https://img.youtube.com/vi/9Bmh6vaQt0s/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "9Bmh6vaQt0s", genre: "YouTube", isSpecial: false },
  { id: 385, title: "Track 385", artist: "YouTube Music", cover: "https://img.youtube.com/vi/WKbwopSXLWU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "WKbwopSXLWU", genre: "YouTube", isSpecial: false },
  { id: 386, title: "Track 386", artist: "YouTube Music", cover: "https://img.youtube.com/vi/gTXiALHJPBU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "gTXiALHJPBU", genre: "YouTube", isSpecial: false },
  { id: 387, title: "Track 387", artist: "YouTube Music", cover: "https://img.youtube.com/vi/bzSTpdcs-EI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "bzSTpdcs-EI", genre: "YouTube", isSpecial: false },
  { id: 388, title: "Track 388", artist: "YouTube Music", cover: "https://img.youtube.com/vi/zuvla6ABKbs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "zuvla6ABKbs", genre: "YouTube", isSpecial: false },
  { id: 389, title: "Track 389", artist: "YouTube Music", cover: "https://img.youtube.com/vi/HbHpNpIGI7Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "HbHpNpIGI7Q", genre: "YouTube", isSpecial: false },
  { id: 390, title: "Track 390", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cYOB941gyXI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cYOB941gyXI", genre: "YouTube", isSpecial: false },
  { id: 391, title: "Track 391", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2tcGMjvoIsI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2tcGMjvoIsI", genre: "YouTube", isSpecial: false },
  { id: 392, title: "Track 392", artist: "YouTube Music", cover: "https://img.youtube.com/vi/XLf4C-ouONo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "XLf4C-ouONo", genre: "YouTube", isSpecial: false },
  { id: 393, title: "Track 393", artist: "YouTube Music", cover: "https://img.youtube.com/vi/sv41rWnUFro/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "sv41rWnUFro", genre: "YouTube", isSpecial: false },
  { id: 394, title: "Track 394", artist: "YouTube Music", cover: "https://img.youtube.com/vi/lz1-1Q8Gync/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "lz1-1Q8Gync", genre: "YouTube", isSpecial: false },
  { id: 395, title: "Track 395", artist: "YouTube Music", cover: "https://img.youtube.com/vi/GnGhZtIcIh0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "GnGhZtIcIh0", genre: "YouTube", isSpecial: false },
  { id: 396, title: "Track 396", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8v-TWxPWIWc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8v-TWxPWIWc", genre: "YouTube", isSpecial: false },
  { id: 397, title: "Track 397", artist: "YouTube Music", cover: "https://img.youtube.com/vi/N2cPyl83tkQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "N2cPyl83tkQ", genre: "YouTube", isSpecial: false },
  { id: 398, title: "Track 398", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mxWBW--yoiA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mxWBW--yoiA", genre: "YouTube", isSpecial: false },
  { id: 399, title: "Track 399", artist: "YouTube Music", cover: "https://img.youtube.com/vi/jh66Pjtqr4k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "jh66Pjtqr4k", genre: "YouTube", isSpecial: false },
  { id: 400, title: "Track 400", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RJD1fQ15I9Y/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RJD1fQ15I9Y", genre: "YouTube", isSpecial: false },
  { id: 401, title: "Track 401", artist: "YouTube Music", cover: "https://img.youtube.com/vi/PdjC8e7GFWg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "PdjC8e7GFWg", genre: "YouTube", isSpecial: false },
  { id: 402, title: "Track 402", artist: "YouTube Music", cover: "https://img.youtube.com/vi/q5mu9BpGjLs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "q5mu9BpGjLs", genre: "YouTube", isSpecial: false },
  { id: 403, title: "Track 403", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Op_UWVBWj3c/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Op_UWVBWj3c", genre: "YouTube", isSpecial: false },
  { id: 404, title: "Track 404", artist: "YouTube Music", cover: "https://img.youtube.com/vi/s9q_82OQsJE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "s9q_82OQsJE", genre: "YouTube", isSpecial: false },
  { id: 405, title: "Track 405", artist: "YouTube Music", cover: "https://img.youtube.com/vi/dPaZNGRcPK4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "dPaZNGRcPK4", genre: "YouTube", isSpecial: false },
  { id: 406, title: "Track 406", artist: "YouTube Music", cover: "https://img.youtube.com/vi/1pc60L6mBt0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "1pc60L6mBt0", genre: "YouTube", isSpecial: false },
  { id: 407, title: "Track 407", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DMLrGfMxOQA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DMLrGfMxOQA", genre: "YouTube", isSpecial: false },
  { id: 408, title: "Track 408", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Dp6lbdoprZ0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Dp6lbdoprZ0", genre: "YouTube", isSpecial: false },
  { id: 409, title: "Track 409", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2mWaqsC3U7k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2mWaqsC3U7k", genre: "YouTube", isSpecial: false },
  { id: 410, title: "Track 410", artist: "YouTube Music", cover: "https://img.youtube.com/vi/KWA0_kI5PKk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "KWA0_kI5PKk", genre: "YouTube", isSpecial: false },
  { id: 411, title: "Track 411", artist: "YouTube Music", cover: "https://img.youtube.com/vi/UDHklYvDkv8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "UDHklYvDkv8", genre: "YouTube", isSpecial: false },
  { id: 412, title: "Track 412", artist: "YouTube Music", cover: "https://img.youtube.com/vi/YC-0hFZKm4I/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "YC-0hFZKm4I", genre: "YouTube", isSpecial: false },
  { id: 413, title: "Track 413", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yHWPO9DDnsk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yHWPO9DDnsk", genre: "YouTube", isSpecial: false },
  { id: 414, title: "Track 414", artist: "YouTube Music", cover: "https://img.youtube.com/vi/3N3n23loy24/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "3N3n23loy24", genre: "YouTube", isSpecial: false },
  { id: 415, title: "Track 415", artist: "YouTube Music", cover: "https://img.youtube.com/vi/1aQTCPxZre8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "1aQTCPxZre8", genre: "YouTube", isSpecial: false },
  { id: 416, title: "Track 416", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0JLRExeOH-k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0JLRExeOH-k", genre: "YouTube", isSpecial: false },
  { id: 417, title: "Track 417", artist: "YouTube Music", cover: "https://img.youtube.com/vi/30U1M5giElY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "30U1M5giElY", genre: "YouTube", isSpecial: false },
  { id: 418, title: "Track 418", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yZbZiMAyFjs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yZbZiMAyFjs", genre: "YouTube", isSpecial: false },
  { id: 419, title: "Track 419", artist: "YouTube Music", cover: "https://img.youtube.com/vi/rRx88tN2LYo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "rRx88tN2LYo", genre: "YouTube", isSpecial: false },
  { id: 420, title: "Track 420", artist: "YouTube Music", cover: "https://img.youtube.com/vi/iasxMdSu7Jo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "iasxMdSu7Jo", genre: "YouTube", isSpecial: false },
  { id: 421, title: "Track 421", artist: "YouTube Music", cover: "https://img.youtube.com/vi/qTsAdjULqwg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "qTsAdjULqwg", genre: "YouTube", isSpecial: false },
  { id: 422, title: "Track 422", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Njq4A5DAqRw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Njq4A5DAqRw", genre: "YouTube", isSpecial: false },
  { id: 423, title: "Track 423", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Iur99jHJonk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Iur99jHJonk", genre: "YouTube", isSpecial: false },
  { id: 424, title: "Track 424", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LOmC1dlZ2BE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LOmC1dlZ2BE", genre: "YouTube", isSpecial: false },
  { id: 425, title: "Track 425", artist: "YouTube Music", cover: "https://img.youtube.com/vi/rQL4OspO9mI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "rQL4OspO9mI", genre: "YouTube", isSpecial: false },
  { id: 426, title: "Track 426", artist: "YouTube Music", cover: "https://img.youtube.com/vi/75o1iC1OSrE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "75o1iC1OSrE", genre: "YouTube", isSpecial: false },
  { id: 427, title: "Track 427", artist: "YouTube Music", cover: "https://img.youtube.com/vi/1nWQs6IxTrY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "1nWQs6IxTrY", genre: "YouTube", isSpecial: false },
  { id: 428, title: "Track 428", artist: "YouTube Music", cover: "https://img.youtube.com/vi/H2f7MZaw3Yo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "H2f7MZaw3Yo", genre: "YouTube", isSpecial: false },
  { id: 429, title: "Track 429", artist: "YouTube Music", cover: "https://img.youtube.com/vi/K-Ts-NFR62o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "K-Ts-NFR62o", genre: "YouTube", isSpecial: false },
  { id: 430, title: "Track 430", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6d5SS0gS5bU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6d5SS0gS5bU", genre: "YouTube", isSpecial: false },
  { id: 431, title: "Track 431", artist: "YouTube Music", cover: "https://img.youtube.com/vi/iAIBF2ngbWY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "iAIBF2ngbWY", genre: "YouTube", isSpecial: false },
  { id: 432, title: "Track 432", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yy-ELf7JpMw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yy-ELf7JpMw", genre: "YouTube", isSpecial: false },
  { id: 433, title: "Track 433", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AgX2II9si7w/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AgX2II9si7w", genre: "YouTube", isSpecial: false },
  { id: 434, title: "Track 434", artist: "YouTube Music", cover: "https://img.youtube.com/vi/VOLKJJvfAbg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "VOLKJJvfAbg", genre: "YouTube", isSpecial: false },
  { id: 435, title: "Track 435", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Qdz5n1Xe5Qo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Qdz5n1Xe5Qo", genre: "YouTube", isSpecial: false },
  { id: 436, title: "Track 436", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Njq4A5DAqRw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Njq4A5DAqRw", genre: "YouTube", isSpecial: false },
  { id: 437, title: "Track 437", artist: "YouTube Music", cover: "https://img.youtube.com/vi/7mTDBsdfw88/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "7mTDBsdfw88", genre: "YouTube", isSpecial: false },
  { id: 438, title: "Track 438", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DKOLynNhWxo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DKOLynNhWxo", genre: "YouTube", isSpecial: false },
  { id: 439, title: "Track 439", artist: "YouTube Music", cover: "https://img.youtube.com/vi/NobzfIebbrE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "NobzfIebbrE", genre: "YouTube", isSpecial: false },
  { id: 440, title: "Track 440", artist: "YouTube Music", cover: "https://img.youtube.com/vi/OGI0fNvr4fo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "OGI0fNvr4fo", genre: "YouTube", isSpecial: false },
  { id: 441, title: "Track 441", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LlI1IkgP6BQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LlI1IkgP6BQ", genre: "YouTube", isSpecial: false },
  { id: 442, title: "Track 442", artist: "YouTube Music", cover: "https://img.youtube.com/vi/YR12Z8f1Dh8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "YR12Z8f1Dh8", genre: "YouTube", isSpecial: false },
  { id: 443, title: "Track 443", artist: "YouTube Music", cover: "https://img.youtube.com/vi/t8Z2qM07Ugg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "t8Z2qM07Ugg", genre: "YouTube", isSpecial: false },
  { id: 444, title: "Track 444", artist: "YouTube Music", cover: "https://img.youtube.com/vi/GtQstf_sGr4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "GtQstf_sGr4", genre: "YouTube", isSpecial: false },
  { id: 445, title: "Track 445", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mYSOyDXJ6uM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mYSOyDXJ6uM", genre: "YouTube", isSpecial: false },
  { id: 446, title: "Track 446", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kyjg5kX4pT0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kyjg5kX4pT0", genre: "YouTube", isSpecial: false },
  { id: 447, title: "Track 447", artist: "YouTube Music", cover: "https://img.youtube.com/vi/HIrktxMHhQU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "HIrktxMHhQU", genre: "YouTube", isSpecial: false },
  { id: 448, title: "Track 448", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JlgkMXex2DI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JlgkMXex2DI", genre: "YouTube", isSpecial: false },
  { id: 449, title: "Track 449", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kl4VNWXaST0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kl4VNWXaST0", genre: "YouTube", isSpecial: false },
  { id: 450, title: "Track 450", artist: "YouTube Music", cover: "https://img.youtube.com/vi/S-ezhTXPVGU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "S-ezhTXPVGU", genre: "YouTube", isSpecial: false },
  { id: 451, title: "Track 451", artist: "YouTube Music", cover: "https://img.youtube.com/vi/YhpxDtR7lfs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "YhpxDtR7lfs", genre: "YouTube", isSpecial: false },
  { id: 452, title: "Track 452", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8kxufj_snhI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8kxufj_snhI", genre: "YouTube", isSpecial: false },
  { id: 453, title: "Track 453", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SQ-qyI3jw40/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SQ-qyI3jw40", genre: "YouTube", isSpecial: false },
  { id: 454, title: "Track 454", artist: "YouTube Music", cover: "https://img.youtube.com/vi/h1mmFW7sgGQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "h1mmFW7sgGQ", genre: "YouTube", isSpecial: false },
  { id: 455, title: "Track 455", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vzlXfZlH5dk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vzlXfZlH5dk", genre: "YouTube", isSpecial: false },
  { id: 456, title: "Track 456", artist: "YouTube Music", cover: "https://img.youtube.com/vi/W15KUnxvZ7A/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "W15KUnxvZ7A", genre: "YouTube", isSpecial: false },
  { id: 457, title: "Track 457", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6vKucgAeF_Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6vKucgAeF_Q", genre: "YouTube", isSpecial: false },
  { id: 458, title: "Track 458", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mfoySJoaMCE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mfoySJoaMCE", genre: "YouTube", isSpecial: false },
  { id: 459, title: "Track 459", artist: "YouTube Music", cover: "https://img.youtube.com/vi/syFZfO_wfMQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "syFZfO_wfMQ", genre: "YouTube", isSpecial: false },
  { id: 460, title: "Track 460", artist: "YouTube Music", cover: "https://img.youtube.com/vi/71EuiHOMk0k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "71EuiHOMk0k", genre: "YouTube", isSpecial: false },
  { id: 461, title: "Track 461", artist: "YouTube Music", cover: "https://img.youtube.com/vi/dnXGxMlV-rU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "dnXGxMlV-rU", genre: "YouTube", isSpecial: false },
  { id: 462, title: "Track 462", artist: "YouTube Music", cover: "https://img.youtube.com/vi/OxXKDGO-MYQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "OxXKDGO-MYQ", genre: "YouTube", isSpecial: false },
  { id: 463, title: "Track 463", artist: "YouTube Music", cover: "https://img.youtube.com/vi/koEh18NcaDY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "koEh18NcaDY", genre: "YouTube", isSpecial: false },
  { id: 464, title: "Track 464", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RIz96zpbeBI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RIz96zpbeBI", genre: "YouTube", isSpecial: false },
  { id: 465, title: "Track 465", artist: "YouTube Music", cover: "https://img.youtube.com/vi/038jmlSH3iM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "038jmlSH3iM", genre: "YouTube", isSpecial: false },
  { id: 466, title: "Track 466", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RaGZIrd2DuU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RaGZIrd2DuU", genre: "YouTube", isSpecial: false },
  { id: 467, title: "Track 467", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yKNxeF4KMsY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yKNxeF4KMsY", genre: "YouTube", isSpecial: false },
  { id: 468, title: "Track 468", artist: "YouTube Music", cover: "https://img.youtube.com/vi/WPwTPhFMm3k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "WPwTPhFMm3k", genre: "YouTube", isSpecial: false },
  { id: 469, title: "Track 469", artist: "YouTube Music", cover: "https://img.youtube.com/vi/dqzxTjzNAPY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "dqzxTjzNAPY", genre: "YouTube", isSpecial: false },
  { id: 470, title: "Track 470", artist: "YouTube Music", cover: "https://img.youtube.com/vi/lpyQhpksHRI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "lpyQhpksHRI", genre: "YouTube", isSpecial: false },
  { id: 471, title: "Track 471", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kDgBQFbwX2Y/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kDgBQFbwX2Y", genre: "YouTube", isSpecial: false },
  { id: 472, title: "Track 472", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6k8Aja80GQM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6k8Aja80GQM", genre: "YouTube", isSpecial: false },
  { id: 473, title: "Track 473", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2FPTVYj3ouE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2FPTVYj3ouE", genre: "YouTube", isSpecial: false },
  { id: 474, title: "Track 474", artist: "YouTube Music", cover: "https://img.youtube.com/vi/VvHOntjmuHY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "VvHOntjmuHY", genre: "YouTube", isSpecial: false },
  { id: 475, title: "Track 475", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-Ecn2pbTcFU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-Ecn2pbTcFU", genre: "YouTube", isSpecial: false },
  { id: 476, title: "Track 476", artist: "YouTube Music", cover: "https://img.youtube.com/vi/UH2cPk24LQw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "UH2cPk24LQw", genre: "YouTube", isSpecial: false },
  { id: 477, title: "Track 477", artist: "YouTube Music", cover: "https://img.youtube.com/vi/eW4At7ozGFQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "eW4At7ozGFQ", genre: "YouTube", isSpecial: false },
  { id: 478, title: "Track 478", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cRbd4eB4g04/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cRbd4eB4g04", genre: "YouTube", isSpecial: false },
  { id: 479, title: "Track 479", artist: "YouTube Music", cover: "https://img.youtube.com/vi/I-Pnr0MQTbU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "I-Pnr0MQTbU", genre: "YouTube", isSpecial: false },
  { id: 480, title: "Track 480", artist: "YouTube Music", cover: "https://img.youtube.com/vi/d7it4DCNFIY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "d7it4DCNFIY", genre: "YouTube", isSpecial: false },
  { id: 481, title: "Track 481", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AQWmqEF7Kpc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AQWmqEF7Kpc", genre: "YouTube", isSpecial: false },
  { id: 482, title: "Track 482", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2vKMY75kvjI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2vKMY75kvjI", genre: "YouTube", isSpecial: false },
  { id: 483, title: "Track 483", artist: "YouTube Music", cover: "https://img.youtube.com/vi/fCFqEI0PCa8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "fCFqEI0PCa8", genre: "YouTube", isSpecial: false },
  { id: 484, title: "Track 484", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AX6OrbgS8lI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AX6OrbgS8lI", genre: "YouTube", isSpecial: false },
  { id: 485, title: "Track 485", artist: "YouTube Music", cover: "https://img.youtube.com/vi/go-j1EpaGVo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "go-j1EpaGVo", genre: "YouTube", isSpecial: false },
  { id: 486, title: "Track 486", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AX6OrbgS8lI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AX6OrbgS8lI", genre: "YouTube", isSpecial: false },
  { id: 487, title: "Track 487", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DxsDekHDKXo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DxsDekHDKXo", genre: "YouTube", isSpecial: false },
  { id: 488, title: "Track 488", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DLZD47lj82o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DLZD47lj82o", genre: "YouTube", isSpecial: false },
  { id: 489, title: "Track 489", artist: "YouTube Music", cover: "https://img.youtube.com/vi/s-bZD3O3P80/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "s-bZD3O3P80", genre: "YouTube", isSpecial: false },
  { id: 490, title: "Track 490", artist: "YouTube Music", cover: "https://img.youtube.com/vi/tfchHFd3CvU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "tfchHFd3CvU", genre: "YouTube", isSpecial: false },
  { id: 491, title: "Track 491", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JgDNFQ2RaLQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JgDNFQ2RaLQ", genre: "YouTube", isSpecial: false },
  { id: 492, title: "Track 492", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DbiRVNeZPnw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DbiRVNeZPnw", genre: "YouTube", isSpecial: false },
  { id: 493, title: "Track 493", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Qwm6BSGrOq0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Qwm6BSGrOq0", genre: "YouTube", isSpecial: false },
  { id: 494, title: "Track 494", artist: "YouTube Music", cover: "https://img.youtube.com/vi/aYLJnasivzI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "aYLJnasivzI", genre: "YouTube", isSpecial: false },
  { id: 495, title: "Track 495", artist: "YouTube Music", cover: "https://img.youtube.com/vi/zfWlGsiFDzk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "zfWlGsiFDzk", genre: "YouTube", isSpecial: false },
  { id: 496, title: "Track 496", artist: "YouTube Music", cover: "https://img.youtube.com/vi/sOsn5pEBvm8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "sOsn5pEBvm8", genre: "YouTube", isSpecial: false },
  { id: 497, title: "Track 497", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-3d1PB3SU3c/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-3d1PB3SU3c", genre: "YouTube", isSpecial: false },
  { id: 498, title: "Track 498", artist: "YouTube Music", cover: "https://img.youtube.com/vi/s-bZD3O3P80/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "s-bZD3O3P80", genre: "YouTube", isSpecial: false },
  { id: 499, title: "Track 499", artist: "YouTube Music", cover: "https://img.youtube.com/vi/bL6dJjxm0x0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "bL6dJjxm0x0", genre: "YouTube", isSpecial: false },
  { id: 500, title: "Track 500", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JLj0g2XJXHM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JLj0g2XJXHM", genre: "YouTube", isSpecial: false },
  { id: 501, title: "Track 501", artist: "YouTube Music", cover: "https://img.youtube.com/vi/1pAB0wrQTLE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "1pAB0wrQTLE", genre: "YouTube", isSpecial: false },
  { id: 502, title: "Track 502", artist: "YouTube Music", cover: "https://img.youtube.com/vi/3Cp2QTBZAFQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "3Cp2QTBZAFQ", genre: "YouTube", isSpecial: false },
  { id: 503, title: "Track 503", artist: "YouTube Music", cover: "https://img.youtube.com/vi/oB7XOosE3eA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "oB7XOosE3eA", genre: "YouTube", isSpecial: false },
  { id: 504, title: "Track 504", artist: "YouTube Music", cover: "https://img.youtube.com/vi/goPn5HAsNZo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "goPn5HAsNZo", genre: "YouTube", isSpecial: false },
  { id: 505, title: "Track 505", artist: "YouTube Music", cover: "https://img.youtube.com/vi/tLKiqQZcvIY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "tLKiqQZcvIY", genre: "YouTube", isSpecial: false },
  { id: 506, title: "Track 506", artist: "YouTube Music", cover: "https://img.youtube.com/vi/riVOHkYvzjI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "riVOHkYvzjI", genre: "YouTube", isSpecial: false },
  { id: 507, title: "Track 507", artist: "YouTube Music", cover: "https://img.youtube.com/vi/sFMRqxCexDk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "sFMRqxCexDk", genre: "YouTube", isSpecial: false },
  { id: 508, title: "Track 508", artist: "YouTube Music", cover: "https://img.youtube.com/vi/dfCuMoiwN6M/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "dfCuMoiwN6M", genre: "YouTube", isSpecial: false },
  { id: 509, title: "Shape of You (Stormzy Remix)", artist: "Ed Sheeran ft. Stormzy", cover: "https://img.youtube.com/vi/p-GILTkcV4Y/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "p-GILTkcV4Y", genre: "YouTube", isSpecial: false },
  { id: 510, title: "Valleys", artist: "WOAH", cover: "https://img.youtube.com/vi/CwHay-S-yy8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "CwHay-S-yy8", genre: "YouTube", isSpecial: false },
  { id: 511, title: "Socha Hai", artist: "Farhan Akhtar", cover: "https://img.youtube.com/vi/eY62RfeviuE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "eY62RfeviuE", genre: "YouTube", isSpecial: false },
  { id: 512, title: "Sage", artist: "Ritviz", cover: "https://img.youtube.com/vi/_kUrW9SEaJc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "_kUrW9SEaJc", genre: "YouTube", isSpecial: false },
  { id: 513, title: "Yeh Hansta Hua Carvan Zindagi Ka", artist: "Hemant Kumar & Asha Bhosle", cover: "https://img.youtube.com/vi/eaaouSeuLOk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "eaaouSeuLOk", genre: "YouTube", isSpecial: false },
  { id: 514, title: "PLAY DATE", artist: "Melanie Martinez", cover: "https://img.youtube.com/vi/Nxs_mpWt2BA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Nxs_mpWt2BA", genre: "YouTube", isSpecial: false },
  { id: 515, title: "MEHERBANI", artist: "Jubin Nautiyal & Arko", cover: "https://img.youtube.com/vi/c9T8k3A5Tn4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "c9T8k3A5Tn4", genre: "YouTube", isSpecial: false }
];

app.get('/api/songs', (req, res) => {
  res.json(songs);
});

// Fetch real title + artist from YouTube oEmbed for tracks with generic names
async function enrichYouTubeTracks() {
  const toEnrich = songs.filter(s => !s.file && s.ytVideoId && s.title.startsWith('Track '));
  const BATCH = 8; // parallel requests per batch
  for (let i = 0; i < toEnrich.length; i += BATCH) {
    const batch = toEnrich.slice(i, i + BATCH);
    await Promise.all(batch.map(async (song) => {
      try {
        const res = await fetch(
          `https://www.youtube.com/oembed?url=https://youtu.be/${song.ytVideoId}&format=json`
        );
        if (!res.ok) return;
        const data = await res.json();
        if (data.title) song.title = data.title;
        if (data.author_name) song.artist = data.author_name;
        if (data.thumbnail_url) song.cover = data.thumbnail_url;
      } catch (_) {}
    }));
  }
  console.log(`Enriched ${toEnrich.length} YouTube tracks with real metadata`);
}

enrichYouTubeTracks();

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});

