const express = require('express');
const cors = require('cors');

const app = express();
const PORT = 5000;

app.use(cors());

const songs = [
  // Core Collection
  { id: 1, title: "Mortals", artist: "Warriyo ft. Laura Brehm", cover: "/covers/1.jpg", file: "/songs/1.mp3", duration: "3:48", ytVideoId: "ltyf0PjonQg", genre: "Trap" },
  { id: 2, title: "Cielo", artist: "Huma-Huma", cover: "/covers/2.jpg", file: "/songs/2.mp3", duration: "2:02", ytVideoId: "ltyf0PjonQg", genre: "Electronic" },
  { id: 3, title: "Invincible", artist: "DEAF KEV", cover: "/covers/3.jpg", file: "/songs/3.mp3", duration: "4:33", ytVideoId: "5Dkfo0IjoBk", genre: "Gaming EDM" },
  { id: 4, title: "My Heart", artist: "Different Heaven & EH!DE", cover: "/covers/4.jpg", file: "/songs/4.mp3", duration: "4:27", ytVideoId: "5Dkfo0IjoBk", genre: "Dubstep" },
  { id: 5, title: "Heroes Tonight", artist: "Janji ft. Johnning", cover: "/covers/5.jpg", file: "/songs/5.mp3", duration: "3:28", ytVideoId: "jJbr4tzIGBI", genre: "Melodic House" },
  { id: 6, title: "Rabba", artist: "Salam-e-Ishq", cover: "/covers/6.jpg", file: "/songs/6.mp3", duration: "4:15", ytVideoId: "jJbr4tzIGBI", genre: "Bollywood" },
  { id: 7, title: "Sakhiyaan", artist: "Salam-e-Ishq", cover: "/covers/7.jpg", file: "/songs/7.mp3", duration: "3:50", ytVideoId: "jJbr4tzIGBI", genre: "Bollywood" },
  { id: 8, title: "Bhula Dena", artist: "Salam-e-Ishq", cover: "/covers/8.jpg", file: "/songs/8.mp3", duration: "4:40", ytVideoId: "7Pw5qk4wJAw", genre: "Romantic" },
  { id: 9, title: "Tumhari Kasam", artist: "Salam-e-Ishq", cover: "/covers/9.jpg", file: "/songs/9.mp3", duration: "3:30", ytVideoId: "7Pw5qk4wJAw", genre: "Melody" },
  { id: 10, title: "Na Jaana", artist: "Salam-e-Ishq", cover: "/covers/10.jpg", file: "/songs/10.mp3", duration: "4:10", ytVideoId: "7Pw5qk4wJAw", genre: "Lo-Fi" },

  // Special Pro YouTube Stream Stations (Direct In-App Audio)
  { id: 11, title: "NCS 24/7 Top Hits", artist: "NCS Official", cover: "https://img.youtube.com/vi/ltyf0PjonQg/hqdefault.jpg", file: "", ytVideoId: "ltyf0PjonQg", genre: "NCS Electronic", isSpecial: true, tag: "POPULAR" },
  { id: 12, title: "NCS Melodic & Chill Vibes", artist: "NCS Chill", cover: "https://img.youtube.com/vi/jJbr4tzIGBI/hqdefault.jpg", file: "", ytVideoId: "jJbr4tzIGBI", genre: "Chillstep", isSpecial: true, tag: "TRENDING" },
  { id: 13, title: "NCS Gaming Bass & Trap", artist: "NCS Bass", cover: "https://img.youtube.com/vi/5Dkfo0IjoBk/hqdefault.jpg", file: "", ytVideoId: "5Dkfo0IjoBk", genre: "Bass & Trap", isSpecial: true, tag: "GAMING" },
  { id: 14, title: "NCS Cyber Synth & Energy", artist: "NCS Synth", cover: "https://img.youtube.com/vi/Y8ETNh_IQjs/hqdefault.jpg", file: "", ytVideoId: "Y8ETNh_IQjs", genre: "Synthwave", isSpecial: true, tag: "CYBER" },
  { id: 15, title: "NCS Electro & Future House", artist: "NCS Club", cover: "https://img.youtube.com/vi/Z4B4mVV0NzM/hqdefault.jpg", file: "", ytVideoId: "Z4B4mVV0NzM", genre: "Future House", isSpecial: true, tag: "CLUB" },
  { id: 16, title: "NCS Lo-Fi & Ambient Beats", artist: "NCS Lounge", cover: "https://img.youtube.com/vi/7Pw5qk4wJAw/hqdefault.jpg", file: "", ytVideoId: "7Pw5qk4wJAw", genre: "Lo-Fi Chill", isSpecial: true, tag: "RELAX" },
  { id: 17, title: "NCS Phonk & Hard Bass", artist: "NCS Phonk", cover: "https://img.youtube.com/vi/rNXmANj72ps/hqdefault.jpg", file: "", ytVideoId: "rNXmANj72ps", genre: "Phonk & Bass", isSpecial: true, tag: "DRIFT" },
  { id: 128, title: "Track 128", artist: "YouTube Music", cover: "https://img.youtube.com/vi/maNMfH1dVR0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "maNMfH1dVR0", genre: "YouTube", isSpecial: false },
  { id: 129, title: "Track 129", artist: "YouTube Music", cover: "https://img.youtube.com/vi/slM5s55Jz0k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "slM5s55Jz0k", genre: "YouTube", isSpecial: false },
  { id: 130, title: "Track 130", artist: "YouTube Music", cover: "https://img.youtube.com/vi/VNs_cCtdbPc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "VNs_cCtdbPc", genre: "YouTube", isSpecial: false },
  { id: 131, title: "Track 131", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6piRLp7BV8o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6piRLp7BV8o", genre: "YouTube", isSpecial: false },
  { id: 132, title: "Track 132", artist: "YouTube Music", cover: "https://img.youtube.com/vi/nqUN530Rgtw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "nqUN530Rgtw", genre: "YouTube", isSpecial: false },
  { id: 133, title: "Track 133", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-YlmnPh-6rE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-YlmnPh-6rE", genre: "YouTube", isSpecial: false },
  { id: 134, title: "Track 134", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cl0a3i2wFcc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cl0a3i2wFcc", genre: "YouTube", isSpecial: false },
  { id: 135, title: "Track 135", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IltsOcCj1Ak/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IltsOcCj1Ak", genre: "YouTube", isSpecial: false },
  { id: 136, title: "Track 136", artist: "YouTube Music", cover: "https://img.youtube.com/vi/FfOwqhckUH8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "FfOwqhckUH8", genre: "YouTube", isSpecial: false },
  { id: 137, title: "Track 137", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ZUR5E18dvrA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ZUR5E18dvrA", genre: "YouTube", isSpecial: false },
  { id: 138, title: "Track 138", artist: "YouTube Music", cover: "https://img.youtube.com/vi/3ONzh3tf884/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "3ONzh3tf884", genre: "YouTube", isSpecial: false },
  { id: 139, title: "Track 139", artist: "YouTube Music", cover: "https://img.youtube.com/vi/fG70qm6usR8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "fG70qm6usR8", genre: "YouTube", isSpecial: false },
  { id: 140, title: "Track 140", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6RrEQJNZwPQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6RrEQJNZwPQ", genre: "YouTube", isSpecial: false },
  { id: 141, title: "Track 141", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RVh647FkPtA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RVh647FkPtA", genre: "YouTube", isSpecial: false },
  { id: 142, title: "Track 142", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6BYIKEH0RCQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6BYIKEH0RCQ", genre: "YouTube", isSpecial: false },
  { id: 143, title: "Track 143", artist: "YouTube Music", cover: "https://img.youtube.com/vi/TVbI55pDdaI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "TVbI55pDdaI", genre: "YouTube", isSpecial: false },
  { id: 144, title: "Track 144", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8nGFWWJLHio/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8nGFWWJLHio", genre: "YouTube", isSpecial: false },
  { id: 145, title: "Track 145", artist: "YouTube Music", cover: "https://img.youtube.com/vi/jADTdg-o8i0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "jADTdg-o8i0", genre: "YouTube", isSpecial: false },
  { id: 146, title: "Track 146", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vX2cDW8LUWk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vX2cDW8LUWk", genre: "YouTube", isSpecial: false },
  { id: 147, title: "Track 147", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0pWsCiBvLOk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0pWsCiBvLOk", genre: "YouTube", isSpecial: false },
  { id: 148, title: "Track 148", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cWMxCE2HTag/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cWMxCE2HTag", genre: "YouTube", isSpecial: false },
  { id: 149, title: "Track 149", artist: "YouTube Music", cover: "https://img.youtube.com/vi/YsCeMprm2O0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "YsCeMprm2O0", genre: "YouTube", isSpecial: false },
  { id: 150, title: "Track 150", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IAvw60x0Kn4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IAvw60x0Kn4", genre: "YouTube", isSpecial: false },
  { id: 151, title: "Track 151", artist: "YouTube Music", cover: "https://img.youtube.com/vi/pGuc4hPhiKw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "pGuc4hPhiKw", genre: "YouTube", isSpecial: false },
  { id: 152, title: "Track 152", artist: "YouTube Music", cover: "https://img.youtube.com/vi/BWczaSneA0Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "BWczaSneA0Q", genre: "YouTube", isSpecial: false },
  { id: 153, title: "Track 153", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2FhgKp_lfJQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2FhgKp_lfJQ", genre: "YouTube", isSpecial: false },
  { id: 154, title: "Track 154", artist: "YouTube Music", cover: "https://img.youtube.com/vi/5GCfYLguTIs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "5GCfYLguTIs", genre: "YouTube", isSpecial: false },
  { id: 155, title: "Track 155", artist: "YouTube Music", cover: "https://img.youtube.com/vi/3KXZduvOfDo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "3KXZduvOfDo", genre: "YouTube", isSpecial: false },
  { id: 156, title: "Track 156", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mGbkArS9Eyo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mGbkArS9Eyo", genre: "YouTube", isSpecial: false },
  { id: 157, title: "Track 157", artist: "YouTube Music", cover: "https://img.youtube.com/vi/CqDRlVWpzk8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "CqDRlVWpzk8", genre: "YouTube", isSpecial: false },
  { id: 158, title: "Track 158", artist: "YouTube Music", cover: "https://img.youtube.com/vi/bZxtKxiA2qo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "bZxtKxiA2qo", genre: "YouTube", isSpecial: false },
  { id: 159, title: "Track 159", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AsEd5OAys9E/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AsEd5OAys9E", genre: "YouTube", isSpecial: false },
  { id: 160, title: "Track 160", artist: "YouTube Music", cover: "https://img.youtube.com/vi/hjWf8A0YNSE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "hjWf8A0YNSE", genre: "YouTube", isSpecial: false },
  { id: 161, title: "Track 161", artist: "YouTube Music", cover: "https://img.youtube.com/vi/sxUh-Mq1t6Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "sxUh-Mq1t6Q", genre: "YouTube", isSpecial: false },
  { id: 162, title: "Track 162", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cfBLtdg5lYY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cfBLtdg5lYY", genre: "YouTube", isSpecial: false },
  { id: 163, title: "Track 163", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Mz2yP0A3t4o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Mz2yP0A3t4o", genre: "YouTube", isSpecial: false },
  { id: 164, title: "Track 164", artist: "YouTube Music", cover: "https://img.youtube.com/vi/4DfVxVeqk2o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "4DfVxVeqk2o", genre: "YouTube", isSpecial: false },
  { id: 165, title: "Track 165", artist: "YouTube Music", cover: "https://img.youtube.com/vi/N2-HsIYd0Go/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "N2-HsIYd0Go", genre: "YouTube", isSpecial: false },
  { id: 166, title: "Track 166", artist: "YouTube Music", cover: "https://img.youtube.com/vi/WJP1HWB21EI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "WJP1HWB21EI", genre: "YouTube", isSpecial: false },
  { id: 167, title: "Track 167", artist: "YouTube Music", cover: "https://img.youtube.com/vi/E_SbwSe15y0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "E_SbwSe15y0", genre: "YouTube", isSpecial: false },
  { id: 168, title: "Track 168", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mpjNh-uGBY4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mpjNh-uGBY4", genre: "YouTube", isSpecial: false },
  { id: 169, title: "Track 169", artist: "YouTube Music", cover: "https://img.youtube.com/vi/PRXIG7ZWnG8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "PRXIG7ZWnG8", genre: "YouTube", isSpecial: false },
  { id: 170, title: "Track 170", artist: "YouTube Music", cover: "https://img.youtube.com/vi/oMesPehN_Do/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "oMesPehN_Do", genre: "YouTube", isSpecial: false },
  { id: 171, title: "Track 171", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ajGo94h0JxE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ajGo94h0JxE", genre: "YouTube", isSpecial: false },
  { id: 172, title: "Track 172", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8of5w7RgcTc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8of5w7RgcTc", genre: "YouTube", isSpecial: false },
  { id: 173, title: "Track 173", artist: "YouTube Music", cover: "https://img.youtube.com/vi/9T-Zbxg9X_4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "9T-Zbxg9X_4", genre: "YouTube", isSpecial: false },
  { id: 174, title: "Track 174", artist: "YouTube Music", cover: "https://img.youtube.com/vi/bP8ATWCvqzw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "bP8ATWCvqzw", genre: "YouTube", isSpecial: false },
  { id: 175, title: "Track 175", artist: "YouTube Music", cover: "https://img.youtube.com/vi/nJZcbidTutE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "nJZcbidTutE", genre: "YouTube", isSpecial: false },
  { id: 176, title: "Track 176", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0pKGaMHBCII/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0pKGaMHBCII", genre: "YouTube", isSpecial: false },
  { id: 177, title: "Track 177", artist: "YouTube Music", cover: "https://img.youtube.com/vi/25s_TeRqyHg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "25s_TeRqyHg", genre: "YouTube", isSpecial: false },
  { id: 178, title: "Track 178", artist: "YouTube Music", cover: "https://img.youtube.com/vi/KUpwupYj_tY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "KUpwupYj_tY", genre: "YouTube", isSpecial: false },
  { id: 179, title: "Track 179", artist: "YouTube Music", cover: "https://img.youtube.com/vi/jdxM0w253Gg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "jdxM0w253Gg", genre: "YouTube", isSpecial: false },
  { id: 180, title: "Track 180", artist: "YouTube Music", cover: "https://img.youtube.com/vi/b5WF7yZcc1w/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "b5WF7yZcc1w", genre: "YouTube", isSpecial: false },
  { id: 181, title: "Track 181", artist: "YouTube Music", cover: "https://img.youtube.com/vi/mX3RdZGEGDM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "mX3RdZGEGDM", genre: "YouTube", isSpecial: false },
  { id: 182, title: "Track 182", artist: "YouTube Music", cover: "https://img.youtube.com/vi/rmzeFqtk68s/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "rmzeFqtk68s", genre: "YouTube", isSpecial: false },
  { id: 183, title: "Track 183", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ZBMVHhSbF4U/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ZBMVHhSbF4U", genre: "YouTube", isSpecial: false },
  { id: 184, title: "Track 184", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DDYSI_GaNOU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DDYSI_GaNOU", genre: "YouTube", isSpecial: false },
  { id: 185, title: "Track 185", artist: "YouTube Music", cover: "https://img.youtube.com/vi/poT3qmuIarU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "poT3qmuIarU", genre: "YouTube", isSpecial: false },
  { id: 186, title: "Track 186", artist: "YouTube Music", cover: "https://img.youtube.com/vi/T94PHkuydcw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "T94PHkuydcw", genre: "YouTube", isSpecial: false },
  { id: 187, title: "Track 187", artist: "YouTube Music", cover: "https://img.youtube.com/vi/4YbAaRFk70o/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "4YbAaRFk70o", genre: "YouTube", isSpecial: false },
  { id: 188, title: "Track 188", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xRb8hxwN5zc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xRb8hxwN5zc", genre: "YouTube", isSpecial: false },
  { id: 189, title: "Track 189", artist: "YouTube Music", cover: "https://img.youtube.com/vi/08CJzaeH8h4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "08CJzaeH8h4", genre: "YouTube", isSpecial: false },
  { id: 190, title: "Track 190", artist: "YouTube Music", cover: "https://img.youtube.com/vi/E45J_yOyUcA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "E45J_yOyUcA", genre: "YouTube", isSpecial: false },
  { id: 191, title: "Track 191", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DB3D-mtWR0c/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DB3D-mtWR0c", genre: "YouTube", isSpecial: false },
  { id: 192, title: "Track 192", artist: "YouTube Music", cover: "https://img.youtube.com/vi/orYf6VDtj_k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "orYf6VDtj_k", genre: "YouTube", isSpecial: false },
  { id: 193, title: "Track 193", artist: "YouTube Music", cover: "https://img.youtube.com/vi/IZF-rOe9u-g/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "IZF-rOe9u-g", genre: "YouTube", isSpecial: false },
  { id: 194, title: "Track 194", artist: "YouTube Music", cover: "https://img.youtube.com/vi/B4-HoKdW6j0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "B4-HoKdW6j0", genre: "YouTube", isSpecial: false },
  { id: 195, title: "Track 195", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RLzC55ai0eo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RLzC55ai0eo", genre: "YouTube", isSpecial: false },
  { id: 196, title: "Track 196", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JtnPpxe8K7c/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JtnPpxe8K7c", genre: "YouTube", isSpecial: false },
  { id: 197, title: "Track 197", artist: "YouTube Music", cover: "https://img.youtube.com/vi/1nWQs6IxTrY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "1nWQs6IxTrY", genre: "YouTube", isSpecial: false },
  { id: 198, title: "Track 198", artist: "YouTube Music", cover: "https://img.youtube.com/vi/GLGuLXKT9Ng/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "GLGuLXKT9Ng", genre: "YouTube", isSpecial: false },
  { id: 199, title: "Track 199", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8_KBlCKK-0k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8_KBlCKK-0k", genre: "YouTube", isSpecial: false },
  { id: 200, title: "Track 200", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LlI1IkgP6BQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LlI1IkgP6BQ", genre: "YouTube", isSpecial: false },
  { id: 201, title: "Track 201", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8A1XPxaeoZA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8A1XPxaeoZA", genre: "YouTube", isSpecial: false },
  { id: 202, title: "Track 202", artist: "YouTube Music", cover: "https://img.youtube.com/vi/-rmGyJnTKXw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "-rmGyJnTKXw", genre: "YouTube", isSpecial: false },
  { id: 203, title: "Track 203", artist: "YouTube Music", cover: "https://img.youtube.com/vi/CQNJE7ZXHg0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "CQNJE7ZXHg0", genre: "YouTube", isSpecial: false },
  { id: 204, title: "Track 204", artist: "YouTube Music", cover: "https://img.youtube.com/vi/YrJ6OZ7VVWc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "YrJ6OZ7VVWc", genre: "YouTube", isSpecial: false },
  { id: 205, title: "Track 205", artist: "YouTube Music", cover: "https://img.youtube.com/vi/HZHVbmnkuzU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "HZHVbmnkuzU", genre: "YouTube", isSpecial: false },
  { id: 206, title: "Track 206", artist: "YouTube Music", cover: "https://img.youtube.com/vi/3u__IvHX_rI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "3u__IvHX_rI", genre: "YouTube", isSpecial: false },
  { id: 207, title: "Track 207", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LPeZOE8ZIHI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LPeZOE8ZIHI", genre: "YouTube", isSpecial: false },
  { id: 208, title: "Track 208", artist: "YouTube Music", cover: "https://img.youtube.com/vi/piUHBTXsoiY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "piUHBTXsoiY", genre: "YouTube", isSpecial: false },
  { id: 209, title: "Track 209", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vJiDTHrq6DI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vJiDTHrq6DI", genre: "YouTube", isSpecial: false },
  { id: 210, title: "Track 210", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ESpTwlItxpQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ESpTwlItxpQ", genre: "YouTube", isSpecial: false },
  { id: 211, title: "Track 211", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vJQCAtzSfuo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vJQCAtzSfuo", genre: "YouTube", isSpecial: false },
  { id: 212, title: "Track 212", artist: "YouTube Music", cover: "https://img.youtube.com/vi/lBvbNxiVmZA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "lBvbNxiVmZA", genre: "YouTube", isSpecial: false },
  { id: 213, title: "Track 213", artist: "YouTube Music", cover: "https://img.youtube.com/vi/amWKXh9_EQE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "amWKXh9_EQE", genre: "YouTube", isSpecial: false },
  { id: 214, title: "Track 214", artist: "YouTube Music", cover: "https://img.youtube.com/vi/se9DDAwwGQY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "se9DDAwwGQY", genre: "YouTube", isSpecial: false },
  { id: 215, title: "Track 215", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JQuVBmyhW08/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JQuVBmyhW08", genre: "YouTube", isSpecial: false },
  { id: 216, title: "Track 216", artist: "YouTube Music", cover: "https://img.youtube.com/vi/akjdj6iHttY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "akjdj6iHttY", genre: "YouTube", isSpecial: false },
  { id: 217, title: "Track 217", artist: "YouTube Music", cover: "https://img.youtube.com/vi/psXl8w6gQuA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "psXl8w6gQuA", genre: "YouTube", isSpecial: false },
  { id: 218, title: "Track 218", artist: "YouTube Music", cover: "https://img.youtube.com/vi/MOh4qB12vJY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "MOh4qB12vJY", genre: "YouTube", isSpecial: false },
  { id: 219, title: "Track 219", artist: "YouTube Music", cover: "https://img.youtube.com/vi/tsVe7wHl_GQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "tsVe7wHl_GQ", genre: "YouTube", isSpecial: false },
  { id: 220, title: "Track 220", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yDv0WSgXJVg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yDv0WSgXJVg", genre: "YouTube", isSpecial: false },
  { id: 221, title: "Track 221", artist: "YouTube Music", cover: "https://img.youtube.com/vi/8z5GZVURqAg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "8z5GZVURqAg", genre: "YouTube", isSpecial: false },
  { id: 222, title: "Track 222", artist: "YouTube Music", cover: "https://img.youtube.com/vi/M7vXOK_ZKY0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "M7vXOK_ZKY0", genre: "YouTube", isSpecial: false },
  { id: 223, title: "Track 223", artist: "YouTube Music", cover: "https://img.youtube.com/vi/dpwTb9ecLXE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "dpwTb9ecLXE", genre: "YouTube", isSpecial: false },
  { id: 224, title: "Track 224", artist: "YouTube Music", cover: "https://img.youtube.com/vi/c2gSzYLJ8sY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "c2gSzYLJ8sY", genre: "YouTube", isSpecial: false },
  { id: 225, title: "Track 225", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yy-ELf7JpMw/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yy-ELf7JpMw", genre: "YouTube", isSpecial: false },
  { id: 226, title: "Track 226", artist: "YouTube Music", cover: "https://img.youtube.com/vi/udgrClXV26Y/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "udgrClXV26Y", genre: "YouTube", isSpecial: false },
  { id: 227, title: "Track 227", artist: "YouTube Music", cover: "https://img.youtube.com/vi/_mR6bY-ndso/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "_mR6bY-ndso", genre: "YouTube", isSpecial: false },
  { id: 228, title: "Track 228", artist: "YouTube Music", cover: "https://img.youtube.com/vi/KTki8bU8wg8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "KTki8bU8wg8", genre: "YouTube", isSpecial: false },
  { id: 229, title: "Track 229", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ZJ5HxNWYDtM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ZJ5HxNWYDtM", genre: "YouTube", isSpecial: false },
  { id: 230, title: "Track 230", artist: "YouTube Music", cover: "https://img.youtube.com/vi/pmId7mXRKS4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "pmId7mXRKS4", genre: "YouTube", isSpecial: false },
  { id: 231, title: "Track 231", artist: "YouTube Music", cover: "https://img.youtube.com/vi/B7SkAq_94J8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "B7SkAq_94J8", genre: "YouTube", isSpecial: false },
  { id: 232, title: "Track 232", artist: "YouTube Music", cover: "https://img.youtube.com/vi/7Qq4m-bw71g/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "7Qq4m-bw71g", genre: "YouTube", isSpecial: false },
  { id: 233, title: "Track 233", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SivCc33LxyA/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SivCc33LxyA", genre: "YouTube", isSpecial: false },
  { id: 234, title: "Track 234", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xgbgjQWwwIE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xgbgjQWwwIE", genre: "YouTube", isSpecial: false },
  { id: 235, title: "Track 235", artist: "YouTube Music", cover: "https://img.youtube.com/vi/AIWBZbHyNpI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "AIWBZbHyNpI", genre: "YouTube", isSpecial: false },
  { id: 236, title: "Track 236", artist: "YouTube Music", cover: "https://img.youtube.com/vi/t_sCtNmZPwQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "t_sCtNmZPwQ", genre: "YouTube", isSpecial: false },
  { id: 237, title: "Track 237", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xdZiUuwZeOI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xdZiUuwZeOI", genre: "YouTube", isSpecial: false },
  { id: 238, title: "Track 238", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LV_wiOhO40Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LV_wiOhO40Q", genre: "YouTube", isSpecial: false },
  { id: 239, title: "Track 239", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SQ4jZ-EAL88/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SQ4jZ-EAL88", genre: "YouTube", isSpecial: false },
  { id: 240, title: "Track 240", artist: "YouTube Music", cover: "https://img.youtube.com/vi/D9yb5ffKkVo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "D9yb5ffKkVo", genre: "YouTube", isSpecial: false },
  { id: 241, title: "Track 241", artist: "YouTube Music", cover: "https://img.youtube.com/vi/prKlWuv3-PQ/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "prKlWuv3-PQ", genre: "YouTube", isSpecial: false },
  { id: 242, title: "Track 242", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RG-a2kVQcGg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RG-a2kVQcGg", genre: "YouTube", isSpecial: false },
  { id: 243, title: "Track 243", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SMlGGRAB3Hc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SMlGGRAB3Hc", genre: "YouTube", isSpecial: false },
  { id: 244, title: "Track 244", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ilNt2bikxDI/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ilNt2bikxDI", genre: "YouTube", isSpecial: false },
  { id: 245, title: "Track 245", artist: "YouTube Music", cover: "https://img.youtube.com/vi/jfOi7dscWc8/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "jfOi7dscWc8", genre: "YouTube", isSpecial: false },
  { id: 246, title: "Track 246", artist: "YouTube Music", cover: "https://img.youtube.com/vi/SxTYjptEzZs/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "SxTYjptEzZs", genre: "YouTube", isSpecial: false },
  { id: 247, title: "Track 247", artist: "YouTube Music", cover: "https://img.youtube.com/vi/U0EI7XFkkV4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "U0EI7XFkkV4", genre: "YouTube", isSpecial: false },
  { id: 248, title: "Track 248", artist: "YouTube Music", cover: "https://img.youtube.com/vi/GnGhZtIcIh0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "GnGhZtIcIh0", genre: "YouTube", isSpecial: false },
  { id: 249, title: "Track 249", artist: "YouTube Music", cover: "https://img.youtube.com/vi/BWczaSneA0Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "BWczaSneA0Q", genre: "YouTube", isSpecial: false },
  { id: 250, title: "Track 250", artist: "YouTube Music", cover: "https://img.youtube.com/vi/usvVGXFIpTM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "usvVGXFIpTM", genre: "YouTube", isSpecial: false },
  { id: 251, title: "Track 251", artist: "YouTube Music", cover: "https://img.youtube.com/vi/NLKwRW2y-sg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "NLKwRW2y-sg", genre: "YouTube", isSpecial: false },
  { id: 252, title: "Track 252", artist: "YouTube Music", cover: "https://img.youtube.com/vi/a18py61_F_w/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "a18py61_F_w", genre: "YouTube", isSpecial: false },
  { id: 253, title: "Track 253", artist: "YouTube Music", cover: "https://img.youtube.com/vi/TuUVVKVdZm4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "TuUVVKVdZm4", genre: "YouTube", isSpecial: false },
  { id: 254, title: "Track 254", artist: "YouTube Music", cover: "https://img.youtube.com/vi/WPwTPhFMm3k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "WPwTPhFMm3k", genre: "YouTube", isSpecial: false },
  { id: 255, title: "Track 255", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Cb6wuzOurPc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Cb6wuzOurPc", genre: "YouTube", isSpecial: false },
  { id: 256, title: "Track 256", artist: "YouTube Music", cover: "https://img.youtube.com/vi/2mWaqsC3U7k/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "2mWaqsC3U7k", genre: "YouTube", isSpecial: false },
  { id: 257, title: "Track 257", artist: "YouTube Music", cover: "https://img.youtube.com/vi/6vKucgAeF_Q/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "6vKucgAeF_Q", genre: "YouTube", isSpecial: false },
  { id: 258, title: "Track 258", artist: "YouTube Music", cover: "https://img.youtube.com/vi/xHLnZMjJ8bY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "xHLnZMjJ8bY", genre: "YouTube", isSpecial: false },
  { id: 259, title: "Track 259", artist: "YouTube Music", cover: "https://img.youtube.com/vi/b_sCZbYyuO4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "b_sCZbYyuO4", genre: "YouTube", isSpecial: false },
  { id: 260, title: "Track 260", artist: "YouTube Music", cover: "https://img.youtube.com/vi/yIyVhIspa2I/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "yIyVhIspa2I", genre: "YouTube", isSpecial: false },
  { id: 261, title: "Track 261", artist: "YouTube Music", cover: "https://img.youtube.com/vi/dTu5dTEzVM4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "dTu5dTEzVM4", genre: "YouTube", isSpecial: false },
  { id: 262, title: "Track 262", artist: "YouTube Music", cover: "https://img.youtube.com/vi/u7hfwX81bY4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "u7hfwX81bY4", genre: "YouTube", isSpecial: false },
  { id: 263, title: "Track 263", artist: "YouTube Music", cover: "https://img.youtube.com/vi/DKOLynNhWxo/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "DKOLynNhWxo", genre: "YouTube", isSpecial: false },
  { id: 264, title: "Track 264", artist: "YouTube Music", cover: "https://img.youtube.com/vi/ru_5PA8cwkE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "ru_5PA8cwkE", genre: "YouTube", isSpecial: false },
  { id: 265, title: "Track 265", artist: "YouTube Music", cover: "https://img.youtube.com/vi/o1RducJbUdc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "o1RducJbUdc", genre: "YouTube", isSpecial: false },
  { id: 266, title: "Track 266", artist: "YouTube Music", cover: "https://img.youtube.com/vi/HqUeSjsYLNU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "HqUeSjsYLNU", genre: "YouTube", isSpecial: false },
  { id: 267, title: "Track 267", artist: "YouTube Music", cover: "https://img.youtube.com/vi/JbDktrsnH40/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "JbDktrsnH40", genre: "YouTube", isSpecial: false },
  { id: 268, title: "Track 268", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kPtn26x8TZM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kPtn26x8TZM", genre: "YouTube", isSpecial: false },
  { id: 269, title: "Track 269", artist: "YouTube Music", cover: "https://img.youtube.com/vi/QYO6AlxiRE4/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "QYO6AlxiRE4", genre: "YouTube", isSpecial: false },
  { id: 270, title: "Track 270", artist: "YouTube Music", cover: "https://img.youtube.com/vi/RbcG85TK-wM/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "RbcG85TK-wM", genre: "YouTube", isSpecial: false },
  { id: 271, title: "Track 271", artist: "YouTube Music", cover: "https://img.youtube.com/vi/kyDXsLhlwv0/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "kyDXsLhlwv0", genre: "YouTube", isSpecial: false },
  { id: 272, title: "Track 272", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0gLqP1IZUPg/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0gLqP1IZUPg", genre: "YouTube", isSpecial: false },
  { id: 273, title: "Track 273", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Rwy8nryH3gY/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Rwy8nryH3gY", genre: "YouTube", isSpecial: false },
  { id: 274, title: "Track 274", artist: "YouTube Music", cover: "https://img.youtube.com/vi/cWMxCE2HTag/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "cWMxCE2HTag", genre: "YouTube", isSpecial: false },
  { id: 275, title: "Track 275", artist: "YouTube Music", cover: "https://img.youtube.com/vi/k85UB5b6pJU/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "k85UB5b6pJU", genre: "YouTube", isSpecial: false },
  { id: 276, title: "Track 276", artist: "YouTube Music", cover: "https://img.youtube.com/vi/vsWxs1tuwDk/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "vsWxs1tuwDk", genre: "YouTube", isSpecial: false },
  { id: 277, title: "Track 277", artist: "YouTube Music", cover: "https://img.youtube.com/vi/LK7-_dgAVQE/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "LK7-_dgAVQE", genre: "YouTube", isSpecial: false },
  { id: 278, title: "Track 278", artist: "YouTube Music", cover: "https://img.youtube.com/vi/XTp5jaRU3Ws/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "XTp5jaRU3Ws", genre: "YouTube", isSpecial: false },
  { id: 279, title: "Track 279", artist: "YouTube Music", cover: "https://img.youtube.com/vi/Fbv6-50S1lc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "Fbv6-50S1lc", genre: "YouTube", isSpecial: false },
  { id: 280, title: "Track 280", artist: "YouTube Music", cover: "https://img.youtube.com/vi/0dXiVYq8HBc/hqdefault.jpg", file: "", duration: "LIVE", ytVideoId: "0dXiVYq8HBc", genre: "YouTube", isSpecial: false }
];

app.get('/api/songs', (req, res) => {
  res.json(songs);
});

app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});

